### ISSUE TITLE
Wallet header color does not respect Windows dark theme setting

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#109]
A friend of mine reported this issue to me. As seen in the screenshot, all other apps headers are in dark mode, but our wallet still has a bright header.

![image](https://user-images.githubusercontent.com/1579899/149364909-d60e8a02-fda9-4832-893a-f6eacfc6a6c3.png)

**Comment by nop33** [comment]
I think this is more complicated than it looks.

Have a look here: https://stackoverflow.com/questions/46222035/set-color-of-windows-titlebar-electron-js

and here: https://www.npmjs.com/package/custom-electron-titlebar

**Comment by lf94** [comment]
I think https://github.com/electron/electron/issues/23479 gives a better understanding of the issue and better solutions than the two you've linked. I agree, it looks non-trivial to deal with as a web developer.

As someone said concisely:

> Electron has implemented a fix, however it uses nonpublic APIs and is therefore gated behind a build flag (https://github.com/electron/electron/issues/23479#issuecomment-712897558).

We can opt to use this build flag or ignore the issue. IMO as long as we "keep on top" of using the nonpublic API, it's ok, since this is just for non-consequential eye-candy.

**Comment by nop33** [comment]
If this is the fix, and we can verify that it works (in need of a windows machine), then I say let's just fix it.

**Comment by LeeAlephium** [comment]
I'll haul my Windows machine out from the basement to test since I need it anyway to access some drives...

**Comment by LeeAlephium** [comment]
https://github.com/electron/electron/releases/tag/v20.0.0 Added immersive dark mode

**Comment by LeeAlephium** [comment]
Well my Window's machine appears to be dead. It won't power on at all... Going to ask some users in the Discord.

**Comment by LeeAlephium** [comment]
Confirmed working by cgi-bin! :sparkles: Even says it works without restarting the application.

![unknown](https://user-images.githubusercontent.com/105806603/186216991-6fb6428b-aa8e-4a4e-bead-af0dc1e847d5.png)

**Comment by LeeAlephium** [comment]
Confirmed working by @sven-hash! :sparkles: Even says it works without restarting the application.

![unknown](https://user-images.githubusercontent.com/105806603/186218313-354a1071-7d08-4f23-a914-6d457346e58c.png)
