### ISSUE TITLE
Web extension: enable opening the wallet as a tab instead of a popup

### ISSUE THREAD

**Issue by chloekek** [alephium/desktop-wallet#11]
When clicking the web extension toolbar icon it shows the wallet as a popup. Problem is that this popup is modal, so you can’t do anything else on the computer while the wallet is open; doing so will close the popup. It would be nice if there was a button to open the wallet as a browser tab.

Using alephium-wallet 0.10.2 in Firefox.

<details>

<summary>Click here to view screen recording</summary>

![Screen recording demonstrating the problem](https://user-images.githubusercontent.com/50083900/133685659-50b91c0e-8824-44bb-9c71-c49a4aa923e2.gif)

</details>

**Comment by lf94** [comment]
Once again: desktop-wallet does not support being a web extension.
