### ISSUE TITLE
Ensure compatibility with rc releases of node, explorer backend, and alephium-js

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#170]
- node: [v1.3.0-rc6](https://github.com/alephium/alephium/tree/v1.3.0-rc6)
- explorer-backend: [v1.6.0-rc2](https://github.com/alephium/explorer-backend/tree/v1.6.0-rc2)
- alephium-js: ~~[v1.1.3-rc0](https://github.com/alephium/alephium-js/tree/1.1.3-rc0)~~ v1.2.0-rc1

**Comment by lf94** [comment]
Were you able to get node and explorer-backend behaving together?

**Comment by nop33** [comment]
Yes. But I couldn't get the wallet to work yet cause schemas have been changed. Thus, this task.
