### ISSUE TITLE
Allow importing (NOT CREATING) wallets with less than 24 words seed in the desktop wallet. 

### ISSUE THREAD

**Issue by MaudSimon** [alephium/desktop-wallet#172]
**Is your feature request related to a problem? Please describe.**
It is possible to create a wallet with less than 24 words seed via the node. However, the desktop wallet only allows to import wallet with 24 words seed. Which means someone that first created their wallet via the node with less than 24 words seed cannot import it to the desktop wallet. 
This problem was encountered by at least one user: https://www.reddit.com/r/Alephium/comments/tj7gzi/cannot_import_wallet_15_vs_24_words/

**Describe the solution you'd like**
Ideally, the desktop wallet would allow importing wallet with less than 24 words seed. In addition to that, we may want to consider restricting the node wallet and only allowing 24 words seed there too (feature on the desktop wallet would probably still be needed for the existing less than 24 words seed wallets, even though people could just migrate their funds).

**Comment by nop33** [comment]
It should be easy to allow import of wallet with less than 24 words. @polarker @mvaivre, is this request verified and should be implemented? Or is it still at discussion phase?

**Comment by mvaivre** [comment]
I've quickly discussed this with Maud yesterday. I don't see any issue allowing importing any mnemonic length, as long as we keep enforcing 24 words on creation. I'd like @polarker to confirm that it's fine for him too :)

**Comment by tdroxler** [comment]
it's acualy not "any" size but: [12, 15, 18, 21, 24](https://github.com/alephium/alephium/blob/5b5e8cf1eecc9d16a5feda5616e9095834c6b201/crypto/src/main/scala/org/alephium/crypto/wallet/Mnemonic.scala#L54), tho I can't remember why those numbers.

**Comment by polarker** [comment]
The only strict rule is that the mnemonic length should be at least 12 words to make it secure enough. `12, 15, 18, 21, 24` is just a tradition from Bitcoin as far as I remember

**Comment by polarker** [comment]
Passphrase sometimes is considered as the 13-th or 25-th words. So if you see length of 13 or 25, it might be due to passphrase.

**Comment by nop33** [comment]
So, I interpret all the above comments as "yes, we want this feature, go ahead and implement it".

**Comment by polarker** [comment]
This is definitely good to have as some people use the same mnemonic for different coins and different wallets
