### ISSUE TITLE
Not able to scroll through addresses with the mouse wheel

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#174]
![image](https://user-images.githubusercontent.com/6715943/159703503-d64bf065-81c9-4548-b1be-d5ced6568518.png)

Horizontal scrolling doesn't seem to work with a real mouse wheel (no trackpad).

**Comment by nop33** [comment]
This might help

https://alvarotrigo.com/blog/scroll-horizontally-with-mouse-wheel-vanilla-java/
