### ISSUE TITLE
Create a test for broken links

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#175]
Many links aren't working right now (https://wiki.alephium.org/Desktop-Wallet-Guide.html#utxo-consolidation https://wiki.alephium.org/Desktop-Wallet-Guide.html#creating-a-mining-wallet-with-4-addresses). 

Let's add a test to catch any broken link?

**Comment by nop33** [comment]
These are not working because we haven't published the wiki articles!

**Comment by nop33** [comment]
https://github.com/alephium/wiki/pull/46

**Comment by lf94** [comment]
It seems the links themselves are broken, the appropriate links are:

* https://wiki.alephium.org/wallet/Desktop-Wallet-Guide#utxo-consolidation
* https://wiki.alephium.org/wallet/Desktop-Wallet-Guide#creating-a-mining-wallet-with-4-addresses

**Comment by lf94** [comment]
Creating a test which relies on an external service isn't great; I suggest we just make sure the links are deployed already / near the same time.

**Comment by mvaivre** [comment]
IMO we will never be able to ensure that all the links are updated (and that a release is done) ahead of every article change (especially since other non-dev can be responsible for updating the wiki).
I prefer having a test fail rather than a dead link. 
If a test fails and we realise that it's just a temporary issue, we can simply bypass the test. But it would force us to investigate.

**Comment by nop33** [comment]
I think adding a test will become every easier when we start translating our content. We will then have to move all our content to json or yaml or md files. We can then tell a GitHub Actions script to always parse those files, look for links, and validate them. I guess the same can be done with ts files.

**Comment by lf94** [comment]
Do we truly want to test _all_ links to the Internet?

I can create a test that searches for links in our source code and test them all.
