### ISSUE TITLE
Investigation of other blockchain wallets

### ISSUE THREAD

**Issue by polarker** [alephium/desktop-wallet#181]
A list of official or semi-official wallets of other blockchains:

- [avalanche-wallet](https://github.com/ava-labs/avalanche-wallet) is only available on web
- phantom wallet is not open sourced
- polkadot-js is [desktop wallet](https://github.com/polkadot-js/apps) first
- auro [extension wallet](https://github.com/aurowallet/auro-wallet-browser-extension): Mar 28, 2021, [mobile wallet](https://github.com/aurowallet/auro-wallet-mobile-app): Aug 15, 2021
- terra [extension wallet](https://github.com/terra-money/station): Apr 18, 2021, [mobile wallet](https://github.com/terra-money/station-mobile): Mar 29, 2020
- [near-wallet](https://github.com/near/near-wallet) is only available on web

**Comment by nop33** [comment]
@polarker what is the purpose of this task? I have recently created a curated list of wallets that we like (and other resources): https://github.com/orgs/alephium/teams/front-end/discussions/4

Does this satisfy the requirements of this task?
