### ISSUE TITLE
Implement address book

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#182]
**Is your feature request related to a problem? Please describe.**
I regularly send funds to friends of mine and I need to maintain a list of their Alephium addresses outside of the wallet.

**Describe the solution you'd like**
An address book, mapping addresses to names

**Describe alternatives you've considered**
Keeping a list of addresses and names outside of the wallet

**Additional context**
An example of this feature is offered by the [Plug wallet](https://plugwallet.ooo/). It gives you the option to choose an address from your address book when sending a transaction:

![image](https://user-images.githubusercontent.com/1579899/160362456-e92864b2-b3d0-4a48-8124-ac4e7e553561.png)

**Comment by mvaivre** [comment]
Yes, I also had this in mind, that would be very useful. 

It would be easy to implement in a single wallet, but we still need to find a solution regarding account syncing across multiple wallets (same problem with addresses' names & colors). We could offer a metadata export function, or store metadata on GDrive (a la Argent, used for backing up private keys (glups)) or a payload sync through WalletConnect. 

I'll create a task for investigation.

**Comment by tdroxler** [comment]
good idea indeed, regarding syncing I had this idea once to store the wallet settings through a dApps, but haven't thought further if it's doable.

**Comment by mvaivre** [comment]
Superseded by [#355](https://github.com/alephium/desktop-wallet/issues/355)
