### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#191]
Our wallet should respect basic [accessibility conventions](https://www.w3.org/WAI/test-evaluate/preliminary/). We could start by making sure that it's possible to navigate through the app by using the keyboard only.

**Comment by lf94** [comment]
I think no research / investigation needs to happen. The conventions are clear that everything needs to be accessible via the keyboard, mostly by using tab to select next or previous elements and the usual.

**Comment by LeeAlephium** [comment]
All right, I've got my work cut out for me here...

"highlighted" means a border appears around the element

"triggered" means pressing space or enter activates the component

* Wallet selection modal cannot be triggered
* Create / import wallet cannot be highlighted
* Settings tabs cannot be changed
* Theme switcher cannot be highlighted
* Any toggle cannot be highlighted
* Expanding sections cannot be highlighted
* Wallets cannot be deleted
* Menu cannot be navigated to
* Link buttons are not highlighted (but can be triggered)
* Transaction history rows cannot be highlighted
* Addresses rows cannot be highlighted
* More info links cannot be highlighted
* Address color cannot be highlighted
* Address color selector cannot be closed without closing the entire modal
* Address selector cannot be highlighted
* Clipboard in address details cannot be highlighted
* Label in address details cannot be highlighted
* Number of transactions cannot be highlighted
* Total ALPH balance cannot be highlighted
* Nothing in the transaction side pull-out can be highlighted
* Nothing in the Security Check can be highlighted
* Back button in wallet creation can't be highlighted

**Comment by LeeAlephium** [comment]
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex#accessibility_concerns

"Use semantic HTML elements when you can over ARIA"
