### ISSUE TITLE
Alephium wallet

### ISSUE THREAD

**Issue by Raffmanlt** [alephium/desktop-wallet#196]
My Alephium wallet no longer shows a value, no numbers displayed.  This was working fine before.

**Comment by polarker** [comment]
> My Alephium wallet no longer shows a value, no numbers displayed. This was working fine before.

It's probably related to the deployment of our latest release. I will check with the team.

**Comment by lf94** [comment]
Some quick investigation this is due to the pubilc node upgrade not being deployed properly.

**Comment by nop33** [comment]
Is the problem solved? Can this be closed?

**Comment by lf94** [comment]
Yep, resolved since last night.
