### ISSUE TITLE
Order of AddressSummaryCards is changing

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#202]
Seems like the order is not enforced, and can change arbitrarily on fetch.

https://user-images.githubusercontent.com/6715943/162974453-fb488840-1333-4edb-8355-874334c5ee5b.mov

**Comment by nop33** [comment]
Hm, I cannot reproduce. How did you trigger a new fetch? I tried the "Refresh" button, but the order doesn't change.

**Comment by mvaivre** [comment]
I just waited, navigated to the "addresses" section and back, opened en close the address list...

**Comment by nop33** [comment]
Pushed a fix in the https://github.com/alephium/desktop-wallet/pull/200 PR
