### ISSUE TITLE
Invalid value for: body

### ISSUE THREAD

**Issue by oskitar-git** [alephium/desktop-wallet#214]
I'm trying to send token, but my desktop Alephium wallet says:

_**Invalid value for: body (missing keys in dictionary: alphAmount at index 191: decoding failure)**_

![image](https://user-images.githubusercontent.com/13051863/163291158-fd975a41-40de-4987-898a-db849a48d1d1.png)

![image](https://user-images.githubusercontent.com/13051863/163291102-cb55b6ae-d9c5-47e9-9856-893f203b0cb5.png)

Thank you for your assistance

**Comment by lf94** [comment]
You must update to 1.2.0, we had a network update today. Starting at 1.2.0 you will be notified now when to update.

**Comment by oskitar-git** [comment]
> You must update to 1.2.0, we had a network update today. Starting at 1.2.0 you will be notified now when to update.

Ah ok, thank you for your soon response.

I'm new on this platform, so I have one question left: how I have to perform the wallet update safely ?? The wallet app will update automatically??

**Comment by lf94** [comment]
Simple download the new release - nothing else needs to be done. In this new release, the wallet will take your to the GitHub Releases page automatically. We don't do automatic updates for user safety.

https://github.com/alephium/desktop-wallet/releases/tag/v1.2.0 Enjoy! If everything is good after the update please close the issue :slightly_smiling_face:

**Comment by oskitar-git** [comment]
> Simply download the new release - nothing else needs to be done. In this new release, the wallet will take your to the GitHub Releases page automatically when there is an update. We don't do automatic updates for user safety.
> 
> https://github.com/alephium/desktop-wallet/releases/tag/v1.2.0 Enjoy! If everything is good after the update please close the issue 🙂

AH ok, thank you..

If I am not bothering you I would like to ask something that I have not seen in any forum. I have my wallet on windows, and then I installed it on macOS and used the "import wallet" option, I followed the prompts but I have not been able to set up the wallet on macOS so I can use the same ID I have on windows and view my Alephium balance. MacOS wallet always create a new ID and $0 alephium balance.

Do you know a link with instructions to do it?

Thank you!

**Comment by lf94** [comment]
If you imported your seed, you may just have to derive more addresses to see the actual address with funds. I'm not at the office right now but I'll give more details tomorrow.

**Comment by lf94** [comment]
@oskitar-git did you try deriving more addresses? Could you also provide screenshots please?

**Comment by nop33** [comment]
Closing issue since the main topic of the issue was address (wallet upgrade). Feel free to continue the discussion on Discord!
