### ISSUE TITLE
invalid value for:body (missing keys in dictionary: alphAmount at index 192: decoding failure

### ISSUE THREAD

**Issue by deep1532002** [alephium/desktop-wallet#217]
invalid value for:body (missing keys in dictionary: alphAmount at index 192: decoding failure
what can i do to solve this error?

**Comment by lf94** [comment]
Please see https://github.com/alephium/desktop-wallet/issues/214#issuecomment-1098600974 and close this issue if it solves your problem :slightly_smiling_face:

**Comment by nop33** [comment]
Problem gets solved by upgrading to the latest version. Download it from https://github.com/alephium/desktop-wallet/releases/tag/v1.2.0
