### ISSUE TITLE
📢 NEW RELEASE (1.2.0): solves `invalid value for: body` error ⚠️ 

### ISSUE THREAD

**Issue by lf94** [alephium/desktop-wallet#218]
You may have recently discovered the wallet is not working; this is because it's not compatible with the newer public node which has been deployed. You must upgrade to version 1.2.0: https://github.com/alephium/desktop-wallet/releases/tag/v1.2.0

Thank you for your patience and thank you for flying Alephium Airlines :airplane:

**Comment by nop33** [comment]
I think we can close this one, what do you guys think?
