### ISSUE TITLE
Invalid value for: body (missing keys in dictionary: alphAmount at index 192: decoding failure)

### ISSUE THREAD

**Issue by NaurisGLTU** [alephium/desktop-wallet#219]
While trying to transfer tokens, im getting this error message:
Invalid value for: body (missing keys in dictionary: alphAmount at index 192: decoding failure)

**Comment by nop33** [comment]
Hello @NaurisGLTU ! Please read the pinned issue in the [issue tracker](https://github.com/alephium/desktop-wallet/issues) :) Thanks!
