### ISSUE TITLE
Invalid value for: body (missing keys in dictionary: alphAmount at index 192: decoding failure)

### ISSUE THREAD

**Issue by Gabe324** [alephium/desktop-wallet#222]
getting this error when i try to to transfer ALPH 

"Invalid value for: body (missing keys in dictionary: alphAmount at index 192: decoding failure)"

**Comment by mvaivre** [comment]
Please see https://github.com/alephium/desktop-wallet/issues/218 and update your wallet to the latest version. Thanks!
