### ISSUE TITLE
Invalid value for: body (missing keys in dictionary: alphAmount at index 190: decoding failure)

### ISSUE THREAD

**Issue by dawidmosk** [alephium/desktop-wallet#226]
Hi,

I have problem with Desktop Wallet for maybe two weeks. Everything was working great for some time. There was no changes in wallet and pc software. On Android phone is working this same account. I see current balance, history, no additional errors. I transfer amount whole number - for example 6 alephium like in this case (i did try other numbers with dots - no changes - error). Installed again wallet unclean/override - this same issue. Any ideas? 

Win11 Ent.

**Comment by lf94** [comment]
https://github.com/alephium/desktop-wallet/issues/218
