### ISSUE TITLE
Add Export feature to the wallet

### ISSUE THREAD

**Issue by Ploddles** [alephium/desktop-wallet#234]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when there is no way to export transactions to a CSV file. Most other wallets offer this feature which is important to me to be able to import and track everything in a spreadsheet. Also important to enable importing into coin tracking and reporting software for tax filing etc

**Describe the solution you'd like**
Enable CSV export, just like QT wallets do.

**Describe alternatives you've considered**
None applicable.

**Additional context**

**Comment by polarker** [comment]
> **Is your feature request related to a problem? Please describe.** I'm always frustrated when there is no way to export transactions to a CSV file. Most other wallets offer this feature which is important to me to be able to import and track everything in a spreadsheet. Also important to enable importing into coin tracking and reporting software for tax filing etc
> 
> **Describe the solution you'd like** Enable CSV export, just like QT wallets do.
> 
> **Describe alternatives you've considered** None applicable.
> 
> **Additional context**

It's under investigation right now: https://github.com/alephium/explorer/issues/41. Please follow up there.
