### ISSUE TITLE
Problem to sending Alephium coins

### ISSUE THREAD

**Issue by jchauca14** [alephium/desktop-wallet#246]
Hi, i have a problem to sending my alephium coins to Gate.io EXCHANGE. I put my address but i have a message: "Invalid value for: body (missing keys in dictionary: alphAmount at index 193: decoding failure)". I need your help to solve this problem. Thank you.

![Problema alephium](https://user-images.githubusercontent.com/79286319/169718053-0fcf25e4-d0f5-4d5a-acd0-e0980a974df2.jpg)

**Comment by polarker** [comment]
Check here: https://github.com/alephium/desktop-wallet/issues/218 You will need to upgrade your wallet.
