### ISSUE TITLE
Add a "Show developers tools" option

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#250]
This will first be used to show/hide the "Contracts" related actions in the navbar.

**Comment by LeeAlephium** [comment]
Can we delete this as it's part of the dApp PR and not a release issue yet?

**Comment by nop33** [comment]
This is implemented in the v2.0 branch. @mvaivre, shall we close this?

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/1579899/221599763-b1c10dc1-20ca-4a33-92fb-9e730ebefcae.png">

**Comment by nop33** [comment]
Closing since it's merged in v2.0.
