### ISSUE TITLE
WalletConnect Unauthorized pairing update request

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#254]
The following error appears in the console after establishing a connection with a dApp and refreshing the wallet:

```
index.js:1 {context: 'client'} {context: 'client/pairing'} 'Unauthorized pairing update request'
index.js:1 {context: 'client'} {context: 'client/pairing'} Error: Unauthorized pairing update request
    at Engine.handleUpdate (engine.ts:683)
    at async Engine.onUpdate (engine.ts:596)
    at async Engine.onMessage (engine.ts:532)
```

After every new connection and a refresh, the same error gets duplicated:

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/1579899/172327040-5cd70655-80ee-402d-ac94-9155bb44a658.png">

## Steps to reproduce

1. Start dev wallet with `npm run electron-dev`
2. Start devnet with `docker-compose up -d --force-recreate` ([repo](https://github.com/alephium/alephium-stack) to clone)
3. Start voting dApp with `npm start` ([repo](https://github.com/alephium/voting-demo) to clone)
4. Change wallet network to localhost
5.  Login to a wallet
6. Connect wallet to dApp
7. Refresh wallet

**Comment by nop33** [comment]
The error does not appear when commenting out the wallet connect client initialization. However, our error handling does not catch this error.

**Comment by LeeAlephium** [comment]
It may not be a trivial error: IIRC this is coming deep within WalletConnect and may not be "catchable". I remember really being stuck on it and looking through WalletConnect's own code. I'll look at another time to try and resolve it again...

**Comment by LeeAlephium** [comment]
This issue is resolved by updating the underlying walletconnect packages. For now it's irrelevant because dApp / WC functionality is not official yet, so this issue is recording information that should instead reside in a PR (which it does).
