### ISSUE TITLE
[$20 USD of ALPH] Improve Windows onboarding when building from scratch

### ISSUE THREAD

**Issue by LeeAlephium** [alephium/desktop-wallet#256]
The submitted PR must explain the following in a new `BUILDING.md` file under Windows 10 and 11:

* How to install latest NodeJS
* How to install latest git
* How to open a terminal
* How to clone the repository
* How to build the project
* How to install the binary

**Comment by LeeAlephium** [comment]
Good point; done!

**Comment by DhirajSardar** [comment]
Can someone please tell how can i contribute to this issue?

**Comment by DhirajSardar** [comment]
Thank You.

**Comment by JeffNeff** [comment]
Can i please be assigned this? Going to knock it out right now. @LeeAlephium

**Comment by nop33** [comment]
@mvaivre do you think we need this open?

**Comment by mvaivre** [comment]
No.
