### ISSUE TITLE
Error while building the transaction: Invalid value for: body (missing keys in dictionary: attoAlphAmount at index 196: decoding failure)

### ISSUE THREAD

**Issue by LeeAlephium** [alephium/desktop-wallet#259]

**Comment by LeeAlephium** [comment]
Resolved by https://github.com/alephium/js-sdk/pull/112 when updating the version in package.json

**Comment by LeeAlephium** [comment]
Updating the node and explorer apis in js-sdk is all that's needed to correct this.

**Comment by nop33** [comment]
Is this something that is still happening?

**Comment by LeeAlephium** [comment]
Once we merge the api updates, no

**Comment by nop33** [comment]
Not relevant anymore. Closing.
