### ISSUE TITLE
Anyone can delete a wallet, no unlocking required

### ISSUE THREAD

**Issue by LeeAlephium** [alephium/desktop-wallet#261]
Literally anyone can delete a wallet:

https://user-images.githubusercontent.com/105806603/174349216-e84892af-0cbf-46ed-b92d-4f8b9f8fe36a.mp4

**Comment by diomark** [comment]
but this might be good in cases where the wallet password is lost and the user is trying to cleanup?

**Comment by LeeAlephium** [comment]
Ooou, possible.

**Comment by LeeAlephium** [comment]
🫡
