### ISSUE TITLE
wont let me withdraw tokens ?? Stating  invaled value for body ???? please help

### ISSUE THREAD

**Issue by Dannywat61** [alephium/desktop-wallet#262]
![IMG_20220620_150211](https://user-images.githubusercontent.com/97338789/174544408-977e5c5b-d300-444c-a204-c9ba1afca255.jpg)
![IMG_20220620_150211](https://user-images.githubusercontent.com/97338789/174544579-51aaaf7e-4a50-4580-851f-e899ecbcdfdc.jpg)

**Comment by nop33** [comment]
Please check https://github.com/alephium/desktop-wallet/issues/218

**Comment by LeeAlephium** [comment]
@Dannywat61  [https://github.com/alephium/desktop-wallet/issues/218](https://github.com/alephium/desktop-wallet/issues/218) (the email is probably hiding the link)
