### ISSUE TITLE
I can't send my coin from the wallet

### ISSUE THREAD

**Issue by Kzsolt197405** [alephium/desktop-wallet#268]
Hello,

I can't send my coins, what is the problem? Thank you in advance.
![error](https://user-images.githubusercontent.com/60464754/175833533-d7691c3b-22eb-40f7-a43f-64049f200fda.png)

**Comment by mvaivre** [comment]
See https://github.com/alephium/desktop-wallet/issues/218

Please update you wallet, thank you!
