### ISSUE TITLE
Wallet + SDK: Ensure compatibility with explorer-backend 1.8.0

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#276]
**Main Changes**

- The address in the Input is now an optional value, the reason behind this: In some specific edge case, if the corresponding output ref isn't sync, we can't find the address, but it's still better to return the input, rather than missing some information.

- The `Output` schema now is either `AssetOutput` or `ContractOutput`

- **We removed the transaction hash of the Input**, again this one was heavy and complicated to retrieve, while it was use "just" to create a link to the corresponding output-ref tx.

- To handle the above removal of the tx hash, we added a new-endpoint: **/transaction-by-output-ref-key** , you can use the Input.output-ref-key to get the Transaction if a user click on the link.

**Comment by nop33** [comment]
FYI, after merging https://github.com/alephium/js-sdk/pull/115, I published a new release candidate version of the SDK on NPM. Use it to ensure compatibility:

https://www.npmjs.com/package/@alephium/sdk/v/0.0.13-rc.0

**Comment by mvaivre** [comment]
The backend is ready to be tested. Adding this to the "Leman" release.

Note: According to Thomas, the nodes are already rocking Leman changes and support both old and updated clients. This means that we can release the "Leman" update anytime, before the hardfork actually happens.

**Comment by nop33** [comment]
> the nodes

You mean the explorer-backend nodes deployed at https://mainnet-backend.alephium.org ?

**Comment by mvaivre** [comment]
No I meant the alephium 1.4.x nodes :)

**Comment by nop33** [comment]
Closing, since this was taken care of by https://github.com/alephium/desktop-wallet/pull/372
