### ISSUE TITLE
Error messages shows for every selected word after the 12 word when importing a wallet

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#277]
**Describe the bug**
When importing a wallet, an error shows after the 12th word has been entered.

**To Reproduce**
1. Try to import a wallet
2. Start typing a seed
3. After the 12th word, an error will appear every time you press Enter

**Expected behavior**
The error should only appear when clicking "Continue" and the seed is invalid.

**Screenshots**

https://user-images.githubusercontent.com/1579899/177583543-95929dc3-bd43-4767-8f0d-24b2eefe6661.mp4

**Comment by LeeAlephium** [comment]
> an error will appear every time you press Enter

I guess we need to make the event not bubble to the form

**Comment by LeeAlephium** [comment]
Nope I was going to tackle it next but if you're eager no problem, please self-assign :D

**Comment by nop33** [comment]
If you haven't tackled it by tomorrow I'll do it then! Done for the day, peace out!
