### ISSUE TITLE
Show prices in USD

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#295]
As in the mobile wallet, we will eventually show the available prices in fiat in the desktop wallet. 

Designs for the desktop wallet are pending, but will certainly be inspired by our mobile designs.  

**TODO**

- [ ] Overview mockup
- [ ] Asset page mockup

**Comment by mvaivre** [comment]
Yeah we want to be consistent, so we'll use coingecko for the desktop wallet as well then.
It's something that could be changed easily in the future.

**Comment by nop33** [comment]
@mvaivre Prices are shown in USD and polling is implemented. Shall we close this?

**Comment by nop33** [comment]
I'll close this, feel free to reopen. It's implemented in v2.0
