### ISSUE TITLE
Displayed max balance does not correspond to actual precise total balance

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#296]
@Sakrecoer reported this to me today. Displayed balance is `10.00` but actual balance is `9.996`. This is due to rounding (not fees substraction). We should display a more precise total to the user.

| Problem | Solution 1 | Solution 2 |
| -------- | -------- | -------- |
| | This might get a bit too long, but at least the value will correspond to the same value the input field will have | Since the lowest value of a transaction is `0.002`, then rounding up at the next decimal should be enough |
| <img alt="image" src="https://user-images.githubusercontent.com/1579899/179482999-45f87e44-f954-417f-8131-56cc0cddaa94.png"> | ![image](https://user-images.githubusercontent.com/1579899/179483501-4d69efdc-8647-4a73-b3fd-a7d7a752e174.png) | ![image](https://user-images.githubusercontent.com/1579899/179483527-0a44d57c-cba6-44d0-bb64-d3c79e4c3e7c.png) |

@mvaivre which solution do you think is better?

**Comment by Sakrecoer** [comment]
Still happening in rc4 @nop33 ...

![image](https://user-images.githubusercontent.com/3484593/179542679-22d51e8d-22bc-46a2-9c64-a1cad4478223.png)

![image](https://user-images.githubusercontent.com/3484593/179542740-f3ff418d-cced-446a-b889-75ac02a38fc0.png)
