### ISSUE TITLE
Address from/to not clear on Overview 

### ISSUE THREAD

**Issue by LeeAlephium** [alephium/desktop-wallet#301]
On an address's transaction overview it's clear where funds are traveling because it shows "To/From"

![1658140876](https://user-images.githubusercontent.com/105806603/179536636-e8cc2e25-0e0b-439d-8807-80f7c2b6a870.png)

But it's very unclear on the Overview

![1658140869](https://user-images.githubusercontent.com/105806603/179536686-144a5b8a-dfa7-4b88-9a62-f87e7950725c.png)

**Comment by mvaivre** [comment]
So, after taking a second look at my mockups, with a colder head (literally) : the idea was to keep the overview TX history uncluttered. But I agree that the current state can be confusing.

I've updated my mockups with a more complete table (note the updated - more lightweight - icons and labels, inspired by the work on the mobile version).

<img width="934" alt="image" src="https://user-images.githubusercontent.com/6715943/179685650-cc7be1ed-38f8-4d8b-87c2-1dcfe6c3cdb4.png">

I'm not yet sure if this is t0o dense or if it's fine. If too dense, we may remove the address label, and keep the same info as in the address's transaction overview.

**Comment by mvaivre** [comment]
Less cluttered :

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/6715943/179718172-b0ed35ff-b61d-48bc-a1e9-c675143509a6.png">

**Comment by LeeAlephium** [comment]
Should the new address badges be reflected in the entire application? Currently that's what I've done...

**Comment by mvaivre** [comment]
> Should the new address badges be reflected in the entire application? Currently that's what I've done...

Yes. Thanks :)

**Comment by LeeAlephium** [comment]
I'm going to extend the width a bit on the cards, the names are not useful anymore otherwise

![1659443375](https://user-images.githubusercontent.com/105806603/182374962-f00a74fd-ae55-4b6c-8f47-9596e1b567a2.png)

**Comment by mvaivre** [comment]
Yeah. This section will eventually need to be redesigned. I'll take some inspiration from my work on the mobile wallet.
Two things:

- Could you center the label horizontally? :) 
- This scrollbar is ugly. I think we could switch to a css scrollbar mimicking the MacOS one (which is IMO way more discreet and elegant). I'll create a task.

**Comment by LeeAlephium** [comment]
The current `api-explorer.ts` doesn't seem to support tokens yet in the `Transaction` interface. For now I'll just use "ALPH" by default

**Comment by LeeAlephium** [comment]
Do we want to reflect the new transaction history design on the address details page as well? This is currently what I'm doing since UX consistency seems like a good goal. I would hide the address label but that's about all I can imagine that would need to be different...

**Comment by mvaivre** [comment]
Yes.
