### ISSUE TITLE
Use custom CSS scrollbars for consistent look across OSes

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#313]
The appearance of the scrollbars on MacOS and most Linux distros is 🤢, especially with the dark theme on.

![image](https://user-images.githubusercontent.com/6715943/182387257-874c5f01-4e10-4079-b83e-3bc5232fa33b.png)

Good news: we know for sure that we're running on webkit! Thus, we don't have to use JS to create pseudo-scrollbars, we can leverage this: https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

**Comment by LeeAlephium** [comment]
@mvaivre or @nop33 what does macos do when the scrollbar is on a black background? Does it turn light grey?

**Comment by nop33** [comment]
yes

<img width="87" alt="image" src="https://user-images.githubusercontent.com/1579899/183706843-5cb438c4-a522-4367-883b-a682b139e2d1.png">

**Comment by mvaivre** [comment]
As a reference, here's a demo of scrollbar interactions on macos. I doubt we can do exactly that with CSS only, but let's try to follow this minimalistic approach!

https://user-images.githubusercontent.com/6715943/183846304-2b728f82-af31-4211-acfd-a93fb995e6ba.mov

**Comment by LeeAlephium** [comment]
@mvaivre to be sure, you saw https://github.com/alephium/desktop-wallet/pull/324#issuecomment-1209775360, and we want something that is much closer to the video demo, right?

**Comment by mvaivre** [comment]
I had not see it nope! It's a very good start, thanks. Ideally yes, we'd like it to be closer to what's shown above:
- With a little padding so that it doesn't touch the side of the window
- A bit less contrasty (less dark / light, depending on the active theme)
- Let's make the scrollbars appear only when hovering the scrollable area (a la ledger live, or Slack)

And no track (as you made it).

**Comment by LeeAlephium** [comment]
Adding padding and having nice fade in/out is going to make this way less trivial - Slack for example creates a scrollbar component and uses this. I'll do the same then if we want these... At least we'll have very configurable scrollbars then :laughing:

**Comment by LeeAlephium** [comment]
https://github.com/malte-wessel/react-custom-scrollbars/issues/406 :facepalm:

**Comment by LeeAlephium** [comment]
https://github.com/xobotyi/react-scrollbars-custom is working perfectly, I just have to adjust a few other places in the application where scrollbars appear and it's all good
