### ISSUE TITLE
UI refresh

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#320]
While we want to keep some visual specificities between the mobile and desktop wallet, we believe that the desktop version could benefit from some visual paradigms developed for the mobile version. 

This is going to be the chance for us to improve on some little visual details and deliver a near-perfect, well balanced UI ;)

**TODO:**

- [ ] Mockups: update addresses management UI
- [ ] Mockups: update / create assets related UI's (implemented in a later release)
- [ ] #436 
- [x] #316 
- [x] #317 
- [x]  #313

**Comment by nop33** [comment]
I propose we close this issue in favor of all other issues I just created. @mvaivre, I leave this up to u
