### ISSUE TITLE
Error while fetching data for address WALLET : (502) Unexpected token B in JSON at position 0

### ISSUE THREAD

**Issue by Magosombra** [alephium/desktop-wallet#325]
**Describe the bug**
In Spanish
Cuando ingreso a la aplicacion de escritorio, ingreso mi usuario y clave, en cuanto deberia ver mis fondos sale el error mencionado en el titulo.

English Translate
When I enter the desktop application, I enter my username and password, as soon as I should see my funds, the error mentioned in the title appears.

**To Reproduce**
1. Go to 'Alephium V1.3.0 .exe' and open it
2. Enter username and regular password
3. Click on connection refresh

**Expected behavior**
In Spanish
Una vez dentro de mi wallet, deberia ver mis fondos, en este caso veo solo 0.000 y en el historial de transacciones lo mismo.

English Translate
Once inside my wallet, I should see my funds, in this case I see only 0,000 and in the transaction history the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/110971607/183861312-0359f7ab-50c1-490a-b148-3cc2178bd2a1.png)

**Environment**
 - OS: Windows 10 Home
 - Version 21H1

**Additional context**
In Spanish
Instantes antes me mostraba el error que mi Wallet estaba offline.

English Traslate
Moments before it showed me the error that my Wallet was offline.

Thanx for all !

**Comment by nop33** [comment]
One of our services to fetch wallet data is down at the moment, we are focusing on bringing it back up ASAP. Sorry for the inconvenience...

**Comment by Iankurtay** [comment]
> One of our services to fetch wallet data (namely the explorer at explorer.alephium.org) is down at the moment, we are focusing on bringing it back up ASAP. Sorry for the inconvenience...

Omg thx bro. i almost got a heart attack xd

**Comment by nop33** [comment]
The issue is resolved. Can you verify? Thanks! ⭐

**Comment by Magosombra** [comment]
Everything works perfect.

Tnx to all team.
