### ISSUE TITLE
Not receiving in my wallet

### ISSUE THREAD

**Issue by Renelavan** [alephium/desktop-wallet#326]
I'm mining through herominers where a minimum payout 0.5 is set. On herominers site it's shown that money has been sent to my wallet, but in my wallet there are no transactions.

Can you please help me solve this issue??

Regards.

**Comment by nop33** [comment]
The problem should be resolved now. Can you confirm? Thanks! 🌸

**Comment by Renelavan** [comment]
Solved, now I see my funds. Thanks!
