### ISSUE TITLE
Alephium 13.0.0

### ISSUE THREAD

**Issue by brutoeiro** [alephium/desktop-wallet#328]
I just upgraded to the last version and lose all my ballance , appear in zero

**Comment by nop33** [comment]
Please check this reply: https://github.com/alephium/desktop-wallet/issues/325#issuecomment-1210390945

**Comment by nop33** [comment]
The problem should be resolved now. Can you confirm? Thanks! 🌸

**Comment by brutoeiro** [comment]
Thank You for You kinndly reply , yes You are right, the issue was resolved.Greetings to the whole team.El 10 ago. 2022 11:48 a. m., Ilias Trichopoulos ***@***.***> escribió:

The problem should be resolved now. Can you confirm? Thanks! 🌸
