### ISSUE TITLE
Wallet shows no transactions and no balance

### ISSUE THREAD

**Issue by dbriel5801** [alephium/desktop-wallet#329]
Just checked on my wallet and it shows no transactions, same on the block explorer. Even after update. Been mining for about 6 weeks and a few payouts per hour. Everything was showing fine last night.

**Comment by nop33** [comment]
Please check this reply: https://github.com/alephium/desktop-wallet/issues/325#issuecomment-1210390945

**Comment by nop33** [comment]
The problem should be resolved now. Can you confirm? Thanks! 🌸

**Comment by dbriel5801** [comment]
Thank you so much
 
-----Original Message-----
