### ISSUE TITLE
Hide change address at a high level

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#331]
I would like to propose that when a Send transaction has “change” outputs going back to the Send address, we do not display it in the transaction details side modal. I think it’s confusing to users. We still (of course) display all the input and output UTXOs in the “Click to see more” expandable section and it’s also displayed in the explorer.

In the example below I would prefer to only see From **Holidays** To **Vault**.

The `(+1)` is also unnecessary there imo.

![image](https://user-images.githubusercontent.com/1579899/184130008-05685f68-bf77-489a-86fa-093fb199ed8b.png)

**Comment by LeeAlephium** [comment]
I agree it should be hidden (and +1 hidden too in this case) - change address is such a passive, natural thing that it's not necessary to explicitly show this always.

Originally I thought it'd be good to educate the user on this point but it really is just noise at the end of the day, and they can check the advanced Outputs section if it really matters.
