### ISSUE TITLE
Copying/pasting wallet address from top bar should copy the full address

### ISSUE THREAD

**Issue by diomark** [alephium/desktop-wallet#334]
If you try to copy the text field that shows the address name/label at the top, it only copies the first part -

i.e. -
![image](https://user-images.githubusercontent.com/20622085/184937574-2de08534-010f-4880-8cc4-59d4908b7666.png)
...simply copies..
★ 18i3yJjaXZ...

I understand we can get the address in other places.. but if a text field is copyable then it should be the full address.. (this is on Windows using wallet 1.3.0)

**Comment by LeeAlephium** [comment]
@diomark would you expect all labels, when copied, to copy the full address?

**Comment by diomark** [comment]
@LeeAlephium I think that'd be a good way to handle it. (when label is copied, copy full address)

**Comment by LeeAlephium** [comment]
@mvaivre seems custom context menus are non-trivial. Are we ok with a little copy button popup beside badges?

![Untitled](https://user-images.githubusercontent.com/105806603/186211944-1ff77fbe-d89e-4c25-acb6-568fda968a28.png)

**Comment by LeeAlephium** [comment]
Related https://github.com/alephium/desktop-wallet/issues/302

**Comment by mvaivre** [comment]
We could do something like this:

<img width="782" alt="image" src="https://user-images.githubusercontent.com/6715943/186439468-6d1b862d-85c3-4ece-93dd-221baf6d57db.png">

Same for labels. For extra clarity, let's add a "Copy address" tooltip when hovering the copy icon.

BTW, motice the different "copy" icon, that we should update in the address detail view :)
