### ISSUE TITLE
import miner wallet

### ISSUE THREAD

**Issue by ferdinandhodl** [alephium/desktop-wallet#336]
**Is your feature request related to a problem? Please describe.**
following the [Desktop Wallet Guide](https://wiki.alephium.org/wallet/Desktop-Wallet-Guide/) a miner wallet consisting of 4 address' can be easily generated. - how can an already existing miner wallet with 4 addresses be imported? - this option seems to be missing.

**Describe the solution you'd like**
miner wallet import option

**Describe alternatives you've considered**
import the first miner wallet address and then adding the 3 remaining address', which actually cannot be done in the existing Desktop Wallet version.

**Comment by nop33** [comment]
The miner wallet is just a wallet. Like any other wallet, it has a 24 word recovery phrase. This phrase can be imported in the desktop wallet. Then, in the welcome screen, one could unfold the _"Advanced settings"_ and recreate the 4 addresses (as described in the [wiki](https://wiki.alephium.org/wallet/Desktop-Wallet-Guide#creating-a-mining-wallet-with-4-addresses). Alternatively, you can recreate the 4 addresses after you unlock your wallet from the _"Addresses"_ screen.

**Comment by ferdinandhodl** [comment]
oh snap! - now I see.
thank you @nop33
