### ISSUE TITLE
Address Badge sizes are inconsistent

### ISSUE THREAD

**Issue by LeeAlephium** [alephium/desktop-wallet#342]
Sometimes a star is larger larger a dot, and then those are sometimes different sizes between modals.

**Comment by mvaivre** [comment]
Thanks for this issue. Could we take this opportunity to make sure that the padding between the start & label is also consistent with the padding between the dot and the label? We may need to reduce the start size a bit.
Thanks!

**Comment by LeeAlephium** [comment]
It should have been consistent but I'll make sure they are :+1:
