### ISSUE TITLE
Listen to OS's theme change and change app's theme accordingly

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#343]
Following #339, let's get the app's theme to change in real-time whenever the OS's theme is updated. And make sure to override the OS theme whenever the user manually change the theme. Persist that change between multiple sessions.

**Comment by LeeAlephium** [comment]
Note for future us: this was already done for Linux and Windows but was problematic on Mac. It seems the issue stems from `nativeTheme`'s `update` event being fired twice.
