### ISSUE TITLE
Use Redux for global state management

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#345]
Taking inspiration from our work on the mobile wallet, let's switch to using Redux to increase state mgmt transparency and predictability.

**Comment by mvaivre** [comment]
As a side note, I just stumbled upon Zustand. 
It's looks quite promising, more and more popular, and I'd really like to get @nop33 opinion on it when he comes back :)
I don't say that we're gonna use it in the desktop wallet instead of redux, but it's worth taking a look before we start the task!

https://www.npmjs.com/package/zustand

**Comment by nop33** [comment]
Hey, thanks for sharing this! I just read through the GH readme and it looks like a really neat tool for state management! The Redux Toolkit also provides some of the benefits that Zustand does in comparison to plain Redux. But for a better evaluation, we'd need to try out an in-depth comparison of the 2 tools (how do we do "this" in Redux Toolkit and how in Zustand), see if we have any improvements in performance, dev speed, etc.

**Comment by mvaivre** [comment]
> Maybe it'd be worth to use Zustand in the desktop wallet and Toolkit in the mobile wallet, in parallel, and see what we like the most.

Yes, that's the idea I had in mind! As a side note, we actually use Zustand in the extension already (an heritage from the Argent X wallet) :)

**Comment by nop33** [comment]
I really like how simply Zustand is handling async actions. It is true that it is quite a complicated process in Toolkit (but it's something I quickly got used to so it doesn't cause a big problem).

**Comment by nop33** [comment]
I'll close this due to inactivity and since everything necessary is moved to Redux
