### ISSUE TITLE
Address cards are cut when no overflow

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#348]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/6715943/188398024-8c0ec7f7-4300-4a3e-9854-3cfbd511466f.png">

The cards' bottom is cut when not scrollbar is shown.

**Comment by mvaivre** [comment]
I also realise now that the cards' title isn't centered :

<img width="477" alt="image" src="https://user-images.githubusercontent.com/6715943/188804716-3be8c110-2767-42d4-a7c4-ed43d5bc71b5.png">

**Comment by nop33** [comment]
Was fixed by https://github.com/alephium/desktop-wallet/pull/353
