### ISSUE TITLE
TX's input / output label display is broken 

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#349]
When sending from the wallet main address to any non-labeled address (external), I get this:

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/6715943/188406459-2463dc20-3981-4c9a-8319-a5a807227752.png">

Issues :
- Labels are wrong (destination address);
- The amount displayed is the "rest" UTXO amount, instead of the sent amount. 

cc/ @tdroxler

**Comment by tdroxler** [comment]
This is probably an issue from the explorer-backend 18-rc2, I should fix it soon

**Comment by mvaivre** [comment]
Solved by @tdroxler
