### ISSUE TITLE
Use middle ellipsis for hashes

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#350]
Let's use middle ellipsis for addresses and ids. Ideally, the length should be dynamic to adapt to any parent component.

<img width="134" alt="image" src="https://user-images.githubusercontent.com/6715943/188588393-0e6a9ac2-5702-4f81-adf9-7963f2ae4607.png">

**Comment by mvaivre** [comment]
Depending on backend progress, this could eventually be shipped in 1.4.0.

**Comment by LeeAlephium** [comment]
https://jsfiddle.net/cLweop1n/3/ I've made it as fast as I think is possible

**Comment by nop33** [comment]
This can be closed, right?
