### ISSUE TITLE
Cant install v1.3.0 release - Windows 64bit

### ISSUE THREAD

**Issue by mk564** [alephium/desktop-wallet#354]
Can't install v1.3.0 release for windows 64 bit, keep getting an error message that Alephium wallet is running and can't be closed. Even tried doing the install after rebooting to make sure it wasn't running.
![Error](https://user-images.githubusercontent.com/104260274/188735323-44fc59a2-6729-4b12-bc9b-f7a6a8d7d484.jpg)

If I have the wallet running it does appear to shut it down, but the same error message pops back up to manually close and retry.

When I select "Cancel" I get the following additional error message about failing to uninstall the old version
![Error2](https://user-images.githubusercontent.com/104260274/188735772-c2b9e5ef-747b-4f57-bcd0-60b758002f20.jpg)

Additional Info:
Current version installed is v1.2.0

**Comment by LeeAlephium** [comment]
Thanks for the bug report @mk564 , we'll investigate in the next couple of weeks, as we prepare for a 1.4.0 release. To resolve issues like this is time consuming and we're a small team. We appreciate if you find a solution and report back as well :heart:

**Comment by nop33** [comment]
@mk564 you mentioned you are running Windows 64bit. Which Windows version are you running? 10 or 11?

**Comment by nop33** [comment]
This issue might be related to this bug: https://github.com/electron-userland/electron-builder/issues/6865

@mk564 Any chance you can find another process that includes the word "Alephium" in its name? That would explain why you have this issue and not other windows users that we talked to.

**Comment by mk564** [comment]
@nop33, I'm using Windows 10 Home 64bit edition

**Comment by mk564** [comment]
@nop33, the only other process as far as I can tell with "Alephium" is the installer itself.

**Comment by nop33** [comment]
One more thing that was mentioned on our Discord that might help: Could it be that you did the initial install with the "administrator" windows user and the upgrades with the "normal" one?

Did you try to uninstall the existing version right after rebooting your computer? If you did, could you then install on a clean slate the new version?

So sorry you are going through this, this is really hard to debug.

**Comment by mk564** [comment]
I tried running the Uninstall of 1.2.0.0 version and it won't run since it
thinks Alephium is still running. Even tried rebooting and Uninstaller says
same thing.

**Comment by nop33** [comment]
@mk564 sorry for keeping waiting so long! We just released version 1.5.0, which includes an automatic update system. Could you try installing that one? If that succeeds, you shouldn't have any problems from now on, since the updates happen through the app (no need to manually download and install from the next release on).

**Comment by nop33** [comment]
I'll close this due to inactivity, please feel free to open it again if you have issues with the v1.5.0 version as well!
