### ISSUE TITLE
Contact list

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#355]
TBD more precisely.

Draft:

We want to let our users select a recipient with confidence. One could send a TX to themselves or to an external address.
- To themselves : the user should be able to select the receiving address by selecting its label.
- To an external recipient : a contact list should be available, avoiding copy pasting mistakes.

TODO:

- [ ] Design

**Comment by nop33** [comment]
Possible duplicate of https://github.com/alephium/desktop-wallet/issues/182? 😄

**Comment by mvaivre** [comment]
Yes! I knew there was one task already!

**Comment by nop33** [comment]
@mvaivre shall we close this issue? I think we got everything we need merged in 2.0 already!

**Comment by nop33** [comment]
I'll close this as it's merged in V2.0
