### ISSUE TITLE
Better display of (internal) transactions

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#367]
Right now, internal transactions are displayed in the overview aggregated table as 2 rows.
We could probably do better by merging them, changing the TX symbol, and maybe display the fee.

Also, the "from/to" labelling can be confusing and can be simplified. 

And finally, I'd like to re-use green to display incoming amounts.

**Comment by mvaivre** [comment]
**Suggested evolution**

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/6715943/192229556-ee8165ee-d3a0-42c2-af45-471d7254d943.png">

**Comment by LeeAlephium** [comment]
Love it :)
