### ISSUE TITLE
Payment not received 

### ISSUE THREAD

**Issue by lordliban** [alephium/desktop-wallet#381]
Dears , 
the pool make a withdraw to my wallet address : 1CaAaXb4CjKJeesRfETA9iwZYEjJjcuKAbfnNBJZUifzG
I didnt receive any amount of alphenium.
My adress is on mainnet and the transfer from pool  use  mainnet also . 
yuo can see this payment on this link : https://explorer.alephium.org/#/addresses/1CaAaXb4CjKJeesRfETA9iwZYEjJjcuKAbfnNBJZUifzG

can you help me ?

**Comment by nop33** [comment]
Please find support on our Discord! https://discord.com/channels/747741246667227157/883355707146141737

I'm there now to chat with you :)

**Comment by lordliban** [comment]
Sorry Sir , I think that the discord link not coreccted ?!!
