### ISSUE TITLE
Show a dash instead of 0 balance when offline

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#385]
> I noticed this when transitioning from online to offline mode (after amounts are loaded) - everything turns to "zero" (probably intentional):

![1664391275](https://user-images.githubusercontent.com/105806603/192865508-08f450ab-0d6f-4477-b645-8598001a719b.png)

_Originally posted by @LeeAlephium in https://github.com/alephium/desktop-wallet/issues/378#issuecomment-1261335497_

------      

Let's start by replacing zeros by a dash "-" when in offline mode. 

Ideally, we should use cached data to display last known values, while clearly showing that they may not be up to date by displaying an offline "snackbar" + making the offline icon more visible (red background). 

This would be easier to achieve when we'll use a global state (Redux or other). 
Let me know what you think. If you agree, I'll create a task for an upcoming miletsone.

**Comment by nop33** [comment]
I agree with all the above points. Let's start with the dash for now, and the red background (like on the mobile wallet shield icon).

**Comment by nop33** [comment]
Closed via #388
