### ISSUE TITLE
'send' parameters for lock time / tweak gas settings  are shown as white on white in light mode

### ISSUE THREAD

**Issue by diomark** [alephium/desktop-wallet#402]
It's nearly impossible to see the slider for set lock time / tweak gas settings when in light mode - I have multiple screens, and on one screen I can see the difference, on the other I can't. It's hard to show this in the image below since it's screen-dependent, but I'm sure others will face this as well. 
![image](https://user-images.githubusercontent.com/20622085/194172999-993e2ba8-ed92-4c54-81ac-7c8f5dd5c390.png)

This is under 1.4.0 RC3 in Windows [alephium-wallet-windows-1.4.0-rc.3.exe]

The same sliders are visible in dark mode -
![image](https://user-images.githubusercontent.com/20622085/194173136-edf4ea62-ceaf-4220-b42b-e373c529fe69.png)

**Comment by diomark** [comment]
Here's a camera picture of my side by side screens to better show the problem here.. 

![image](https://user-images.githubusercontent.com/20622085/194173834-765df57a-8cf7-412f-8b9b-72679f560345.png)

**Comment by nop33** [comment]
Thanks a lot @diomark! I'll try to adjust the colors a bit!

**Comment by diomark** [comment]
@nop33 
![PXL_20221006_153819083](https://user-images.githubusercontent.com/20622085/194357652-ca5919e6-b607-45c5-ac5c-c9ab40609bd4.jpg)

**Comment by nop33** [comment]
I adjusted the color in this screenshot. Can you tell me how this screenshot would look like on your laptop? Is it visible now? Thanks!

<img width="633" alt="image" src="https://user-images.githubusercontent.com/1579899/194413439-5bc6cb8f-f685-4a19-bfa2-97c00298d1b6.png">

**Comment by diomark** [comment]
The sliders themselves are visible now. (the gray box around the setting is still not visible but that's not that important..)
Camera pic below -
![image](https://user-images.githubusercontent.com/20622085/194417041-4bd9da8b-0ee4-4612-b397-d705638e2e3f.png)

**Comment by nop33** [comment]
Closed via #403
