### ISSUE TITLE
Code signing step in release toolchain

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#412]
Implement code signing for at least Windows and MacOS to allow for secure auto-update & better trust.

https://www.electronjs.org/docs/latest/tutorial/code-signing

To be discussed with @killerwhile to add that in our distribution tool chain.

**Comment by mvaivre** [comment]
@killerwhile Confirmed that this is going to be implemented in our tool chain, which in turn would allow #141 to be shipped.

**Comment by nop33** [comment]
Is there an update on Windows/Linux code-signing? Cheers!
