### ISSUE TITLE
coins are not available after wallet recovery

### ISSUE THREAD

**Issue by kamalnath420** [alephium/desktop-wallet#421]
my coins are missing after recovering my wallet to another PC

**Comment by mvaivre** [comment]
Hi there. If the the secret phrase you entered is correct, then the words will be there, 100%.

1) Make extra sure that you've properly entered the words. 
2) Make sure that your are using the correct network (mainnet). This can be changed in settings > networks.
3) Do you see any transaction in the transaction history? Make sure that there is no withdraw transaction.

Please get to [our discord channel](alephium.org/discord) for further help, our community is always happy to help!

**Comment by kamalnath420** [comment]
Dear All

All done as per your instructions but  coins are not available.

Thanks
Kamal

**Comment by tdroxler** [comment]
how did you created your wallet the first time? through the desktop-wallet or with the full-node?
If you used the full-node, maybe you had a mnemonic passphrase (known as 25' word)

**Comment by kamalnath420** [comment]
Its a desktop wallet with 24 recovery words..
