### ISSUE TITLE
balance Zero after import the wallet

### ISSUE THREAD

**Issue by kamalnath420** [alephium/desktop-wallet#423]
after reinstalled my wallet with 24 words recovery my balance was zero.
user name - kamalnath.bandara@gmail.com

**Comment by mvaivre** [comment]
Hi there. If the the secret phrase you entered is correct, then the words will be there, 100%.

1) Make extra sure that you've properly entered the correct secret phrase. If you still have access to the first PC, you can display the phrase by going into settings > wallets. 
2) Make sure that your are using the correct network (mainnet). This can be changed in settings > networks.
3) Do you see any transaction in the transaction history? Make sure that there is no withdraw transaction.

Please get to [our discord channel](alephium.org/discord) for further help, our community is always happy to help!
But of course, remember that you should *never* share you secret phrase with *anybody*.
