### ISSUE TITLE
Implement filtering options in Transfers page

### ISSUE THREAD

**Issue by tdroxler** [alephium/desktop-wallet#430]
The explorer-backend is [now exposing an endpoint to fetch txs of an address by a given time range
](https://github.com/alephium/explorer-backend/pull/378)
That could be useful in the wallet if we could use it to search a tx. It's a nice tool in any e-banking, to be able to research a tx around a given date.

Currently we would need to change the page number until finding the right date.

**Comment by nop33** [comment]
@mvaivre Can I proceed with this task? I remember you said there was something to discuss with Thomas, but I don't remember anymore.

**Comment by mvaivre** [comment]
Yes you can. Here's the mockup we're following:
<img width="982" alt="image" src="https://user-images.githubusercontent.com/6715943/224812793-67237675-20fa-4a2e-9818-a400c685ce2c.png">

I wanted to discuss with @tdroxler the possibility to add more query options for filtering (filter by asset or by direction, for instance). For now, we start with the available filters we have (time & addresses)!

**Comment by tdroxler** [comment]
I created https://github.com/alephium/explorer-backend/issues/439 so we can maybe discuss there?

**Comment by nop33** [comment]
@tdroxler I see that the timeranged endpoint only accepts one address. For our purposes, it's not that useful to only get timeragned txs of 1 address, but of multiple, similarly with the POST endpoints just above. By default, the user sees the Transfers page with all addresses enabled (that would mean we need to make 1 request per address). And with the current API rate limits, that slows down our app quite a bit. I wonder if you can do the same you did as for the POST endpoint (whose reason of existence is exactly that, the transaction list :))


![Image](https://user-images.githubusercontent.com/1579899/225343147-1e91957f-580a-4d0e-8056-c90b4f14addc.png)

**Comment by tdroxler** [comment]
Pretty sure it's possible, I'll have a look.

**Comment by mvaivre** [comment]
Thanks a lot @tdroxler! 
While you're looking into this, we'll start with a first implementation reusing what's done in the explorer : allowing export in individual addresses. I've updated the mockups accordingly @nop33 :

<img width="583" alt="image" src="https://user-images.githubusercontent.com/6715943/225715180-f57070c9-31ee-4a9e-a64d-2935478690cc.png">

**Comment by nop33** [comment]
Closing since it's merged in v2.0!
