### ISSUE TITLE
Numbers display: use tabular version of the font instead of mono font

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#436]
See https://rsms.me/inter/#features/tnum

**Comment by nop33** [comment]
Hm, replacing `font-family: monospace` with `font-feature-settings: 'tnum'` does not produce a consistent string length. We need to investigate more how we create this middle ellipsis...

| monospace | tnum |
|--------|-------|
| <img width="399" alt="image" src="https://user-images.githubusercontent.com/1579899/212075659-fba05aaf-e62b-4615-9a61-68d7f1b6ecfd.png"> | <img width="388" alt="image" src="https://user-images.githubusercontent.com/1579899/212075827-d4197f02-b72e-4853-8c75-528dba4e5f26.png"> |

**Comment by nop33** [comment]
the `tnum` is supposed to work for numbers, based on the link you shared:

> Fixed-width numbers are useful for tabular data, where comparing columns across rows is desired.

Maybe that's why it doesn't work with address hashes.

**Comment by nop33** [comment]
@mvaivre Since this only works with numbers, should we keep this issue open?

**Comment by mvaivre** [comment]
I'll close this one in favour of a new one: find a better mono font! 😄
