### ISSUE TITLE
ПОРОЖНІЙ ГАМАНЕЦЬ

### ISSUE THREAD

**Issue by SH11111** [alephium/desktop-wallet#448]
Доброго дня.Зайшов до гаманця, а в ньому немає нічого порожній.Я не розумію як ним користуватись.
![image](https://user-images.githubusercontent.com/70377999/207788620-992fe42f-2f0e-4f56-9d08-d307ded98a1f.png)
![image](https://user-images.githubusercontent.com/70377999/207788751-dfe4deeb-af30-4d7b-a149-bccf9820e039.png)

**Comment by nop33** [comment]
I would recommend upgrading to the latest version: https://github.com/alephium/desktop-wallet/releases/latest

If the issue persists, please, find support at our Discord: https://alephium.org/discord

**Comment by SH11111** [comment]
дякую все виправилось пысля оновлення

чт, 15 груд. 2022 р. о 10:46 Ilias Trichopoulos ***@***.***>
пише:
