### ISSUE TITLE
Fix browser extension layout issues

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#45]
![image](https://user-images.githubusercontent.com/6715943/139821874-2389a35c-9bd9-40c1-a435-c68e3895659c.png)

Time to refine the extension after the release of the desktop ones.

**Comment by nop33** [comment]
Probably related: https://github.com/alephium/alephium-wallet/issues/110

**Comment by lf94** [comment]
We don't support the wallet as a browser extension.
