### ISSUE TITLE
Tweak the tooltip behaviour

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#462]
I would force the tooltip placement to the right only in the nav bar. Also, I would start using the effect "solid" instead of "float" accros the app.
I see that the new version (v5) of react-tooltip allows to configure anchor element using the data-tooltip-* props. This is great as it would allow us to tweak the tooltip behaviour differently in different parts of the app.
We need react@18 to be able to upgrade, cf #463

**Comment by mvaivre** [comment]
@nop33 I think this one can be closed. Can you confirm? :)

**Comment by nop33** [comment]
Confirming (for the v2.0) and closing!
