### ISSUE TITLE
Sending from 1.4.0 wallet results in explorer link which white-pages

### ISSUE THREAD

**Issue by diomark** [alephium/desktop-wallet#475]
**Describe the bug**
I think 1.4.0 (which is technically the main GA release as of today) wallet is using the wrong explorer link. It results in a white-screen when browsing the transaction details.  (note the latest 1.4.1RC3 works  correctly)

**To Reproduce**
1. 'show explorer' on any transaciton - it goes to explorer-v18 instead of explorer.alephium and white-screens.

**Expected behavior**
redirect to the correct explorer

**Screenshots**

**Environment**
Windows 1.40

**Comment by nop33** [comment]
Thanks for letting us know @diomark, we're looking into establishing a proper redirect rule!

**Comment by nop33** [comment]
This should have been fixed now that we have 1.5.2. @diomark shall we close this, or do we still need it?
