### ISSUE TITLE
desktop wallet issue

### ISSUE THREAD

**Issue by moejaber89** [alephium/desktop-wallet#480]
Hello, i am having an issue with my alephium desktop wallet as when i login with my user and password it login to the wallet but doesn't show me anything it just go to white windows can't see anything if there any suggestions, thank

**Comment by moejaber89** [comment]
![image](https://user-images.githubusercontent.com/85966006/213805362-ed0c1ac0-0f26-4f68-a13e-30766bb71338.png)

**Comment by saintnx** [comment]
I'm seeing the same issue

**Comment by saintnx** [comment]
resolved after installing latest version of wallet for me 

alephium-wallet
Alephium
1.4.0.0

**Comment by moejaber89** [comment]
Thanks Saintnx,
 I just did that and install the new wallet and it works now
