### ISSUE TITLE
Linux binraries of new release workflow do not work

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#486]
I was testing with Set and Thomas the desktop wallet and specifically the automatic update system. I told them to install [1.4.1](https://github.com/alephium/desktop-wallet/releases/tag/v1.4.1) (which is code-signed and built through [the new release workflow](https://github.com/alephium/desktop-wallet/actions/runs/3984374717) that Benoit created) so that we could see if it would ask them to upgrade to [1.4.2](https://github.com/alephium/desktop-wallet/releases/tag/v1.4.2) (which I temporarily had to make it public, now I made it pre-release again so that our users don't get confused).

They could not install neither the `.deb` file, nor the `AppImage` one on their Linux machines (Set is running KUbuntu and Thomas nixOS). They would both just show a white screen… This might be related to the new release workflow but I am not sure. Windows and macOS work fine.

I tried installing VMs on my mac M1 (with VirtualBox, [UTM](https://mac.getutm.app/) as well as [multipass](https://medium.com/@paulrobu/how-to-run-ubuntu-22-04-vms-on-apple-m1-arm-based-systems-for-free-c8283fb38309)), but it's been hours and I still haven't figured out how to run an amd64 Linux VM.

<details><summary>Thomas got this traceback when running the 1.4.1 AppImage file</summary>

```
Uncompress Alephium-1.4.1.AppImage of type 02 @ offset 188392
[=================================================================================================================================================|] 1987/1987 100%
Alephium-1.4.1.AppImage is now installed in /home/thomas/.cache/appimage-run/530cba668dcab73fdc2d720caf1d84686d38d9f62aaaf516aa65b13d0f37bea1
(node:16697) UnhandledPromiseRejectionWarning: Error: Failed to load image from path '/home/thomas/.cache/appimage-run/530cba668dcab73fdc2d720caf1d84686d38d9f62aaaf516aa65b13d0f37bea1/resources/app.asar/public/icons/logo-48.png'
    at createWindow (/home/thomas/.cache/appimage-run/530cba668dcab73fdc2d720caf1d84686d38d9f62aaaf516aa65b13d0f37bea1/resources/app.asar/public/electron.js:155:16)
    at App.<anonymous> (/home/thomas/.cache/appimage-run/530cba668dcab73fdc2d720caf1d84686d38d9f62aaaf516aa65b13d0f37bea1/resources/app.asar/public/electron.js:227:5)
    at App.emit (node:events:527:28)
(Use `alephium-wallet --trace-warnings ...` to show where the warning was created)
(node:16697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which
was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[16764:0125/155054.992807:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[16803:0125/155055.016789:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

</details>

**Comment by mvaivre** [comment]
I don't know it it helps, but I also have this behaviour (white screen) when running `npm run electron-dev`. I need to reload with cmd + R to see the app loading. Let me build locally and see if I see something similar.

**Comment by nop33** [comment]
I also have this, but I thought it is just a dev thing and it didn't bother me much, the production binaries work fine on macOS and Windows..

**Comment by nop33** [comment]
@mvaivre I think that the white screen you refer to is irrelevant. I have the feeling that the issue with the dev mode is that the command `electron .` is executed before the `npm run start` actually spawns the localhost server at port `3000`. That would explain why a simple refresh fixes this.

But that should not affect the production build at all...

**Comment by nop33** [comment]
I've:
1. installed Ubuntu arm64
2. pulled `master`
3. enabled the devtools also in prod mode in `public/electron.js`
4. build an AppImage
5. and run it with
    ```
    $ ./dist/Alephium-1.4.1-rc.2.AppImage 
    ```

I was expecting to see a white screen with the devtools open, hoping to see an error in there. Instead, I just got the white screen without the devtools. The only traceback I have is what I see in the terminal:

```
(node:61651) UnhandledPromiseRejectionWarning: Error: Failed to load image from path '/tmp/.mount_AlephiiRWX5J/resources/app.asar/public/icons/logo-48.png'
    at createWindow (/tmp/.mount_AlephiiRWX5J/resources/app.asar/public/electron.js:155:16)
    at App.<anonymous> (/tmp/.mount_AlephiiRWX5J/resources/app.asar/public/electron.js:227:5)
    at App.emit (node:events:527:28)
(Use `alephium --trace-warnings ...` to show where the warning was created)
(node:61651) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[61686:0130/145134.216990:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[61728:0130/145134.948028:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[61753:0130/145135.787045:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

This is basically the same thing that Benoit and Thomas have reported.
