### ISSUE TITLE
Proxy socks5 support

### ISSUE THREAD

**Issue by sven-hash** [alephium/desktop-wallet#496]
**Is your feature request related to a problem? Please describe.**
It could be nice to support proxy socks5 to add a privacy layer at network level by using Tor (i2p or Nym) for example, and it could enable user without connections restriction to Internet to use the wallet

**Describe the solution you'd like**
Add the possibility to set a menu where the user could set a proxy socks5 address and port. A connectivity test might be nice but not necessary

**Describe alternatives you've considered**
The user could set a proxy for the whole system but it's not really a solution since it will forces all the connections to go trough

**Additional context**

**Comment by sven-hash** [comment]
Please correct me if I'm wrong but it seems that you're using electron and it could support proxy by starting the app from CLI with `--proxy-server`

https://www.electronjs.org/docs/latest/api/command-line-switches#--proxy-serveraddressport

**Comment by sven-hash** [comment]
It's seems that the application accept `--proxy-server` but I cannot get any connections, might try from home

Just found this https://www.npmjs.com/package/electron-proxy-agent

**Comment by sven-hash** [comment]
So yes, using ` C:\Users\<User>\AppData\Local\Programs\alephium-wallet\Alephium.exe --proxy-server=socks5://proxy.notrustverify.ch:443` is working and connect trough Nym mixnet for example

**Comment by sven-hash** [comment]
For appimage it works well too `alephium-wallet-linux-1.4.0.AppImage --proxy-server=socks5://127.0.0.1:1080`

**Comment by nop33** [comment]
FYI, this is a draft release and only those with access to the repo can access it I think.

**Comment by VDAODAO** [comment]
My feedback @mvaivre 

1 - I couldn't get it to work. 

As soon as I activate the Nym Connect, I then go in the network settings, activate custom URLs and then input the values (127.0.0.1 - 1080) then press "save", the wallet reloads, and stays stuck like this: 

<img width="1197" alt="Capture d’écran 2023-06-22 à 16 01 08" src="https://github.com/alephium/desktop-wallet/assets/42373571/c3413486-6d89-4f89-b3b9-3a027671bece">

At some point the "couldn't connect" error message appears, and the barred wifi symbol is shown up there. 

2 - When switching networks (testnet/mainnet) it disconnects from the proxy (and you'd have to manually enter it again)

3 - Option to save proxy config 

Everytime I have to input the values again - maybe it'd be cool to have a way to save proxies (for future use).

4 - It keeps the proxy settings when i shut down and open the app again, that's cool.

**Comment by polto** [comment]
@VDAODAO your NYM connect is running on the phone and the desktop wallet ... well on the desktop. The 127.0.0.1 is an address only available locally, not across devices.

**Comment by VDAODAO** [comment]
Both NYM connect and the desktop wallet are running on the… desktop here :)I probably did something wrong, but it’s not that :)Sent from my iPhoneOn 22 Jun 2023, at 18:45, polto ***@***.***> wrote:﻿
@VDAODAO your NYM connect is running on the phone and the desktop wallet ... well on the desktop. The 127.0.0.1 is an address only available locally, not across devices.

**Comment by sven-hash** [comment]
If you want to test the wallet trough you will need to use a specific service provider for Nym connect. You can use ours, it already whitelist alephium domain (`AQRRAs9oc8QWXAFBs44YhCKUny7AyLsfLy91pwmGgxuf.CWUKoKA1afSKyw5BnFJJg19UDgnaVATupsFhQpyTEBHJ@EBT8jTD8o4tKng2NXrrcrzVhJiBnKpT1bJy5CMeArt2w`)

Check the screen capture on how to set it. Just type `aqr` and select it 

![](https://i.imgur.com/YLj0w7i.png)
![image](https://github.com/alephium/desktop-wallet/assets/6095048/3509f646-e8c7-440c-8595-65e1b8f2405e)
![image](https://github.com/alephium/desktop-wallet/assets/6095048/9387fece-85bf-4b6f-879e-e10d61b8e89f)
![image](https://github.com/alephium/desktop-wallet/assets/6095048/f7fe1cea-0e9d-467d-9d18-8fbc92378770)

And then connect, normally it should work

If anybody want to drop me the alephium wallet I can test it (I've got a 404 when trying to access the release)

**Comment by polto** [comment]
@VDAODAO sorry, because of the look, I thought it was a mobile app. :)

**Comment by sven-hash** [comment]
I've to say it's pretty slick to use it and easy to setup. Congrats !

Proof of Working
![image](https://github.com/alephium/desktop-wallet/assets/6095048/3bf8f0ec-c23c-49db-aed7-f787a088c94f)

**Comment by VDAODAO** [comment]
It works when I do as @sven-hash says.

Rest of my points stand: 

2 - When switching networks (testnet/mainnet) it disconnects from the proxy (without you knowing) and you'd have to manually enter it again. (maybe we need a small icon on top that tells you when you are (or not) protected, as Little snitch does for example.

3 - Option to save proxy config, that'd be nice to have.

4 - It keeps the proxy settings when i shut down and open the app again, that's cool.

Thanks @mvaivre @nop33 for the cool feature. Thanks @polto @sven-hash for your help, pardon the beotian!
