### ISSUE TITLE
Support api-key for node host

### ISSUE THREAD

**Issue by polarker** [alephium/desktop-wallet#51]
We could config `alephium.api.api-key`  to make the endpoint access limited. @tdroxler is guy to go if you need more details.

**Comment by lf94** [comment]
What is the motivation or user story for this feature?

**Comment by tdroxler** [comment]
You can secure the node's API with an API-Key, but then if a desktop wallet is pointing to that node, it won't be able to make transfer as we can't configure the api-key.

**Comment by lf94** [comment]
> but then if a desktop wallet is pointing to that node, it won't be able to make transfer as we can't configure the api-key.

That's kind of what I was originally thinking; that's why I'd like to see a motivation / user story ... !

**Comment by nop33** [comment]
@tdroxler do you think this is still relevant? Shall we transfer this issue to our new [monorepo](https://github.com/alephium/alephium-frontend/)?

cc @mvaivre

**Comment by tdroxler** [comment]
We didn't see any need over the pas two years, I think we could close this issue and re-open a new one later if needed
