### ISSUE TITLE
Discuss encrypted storage key approach

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#513]
https://github.com/alephium/desktop-wallet/pull/508#discussion_r1099271899

**Comment by mvaivre** [comment]
> My opinion is that this double hashing is completely unnecessary

Indeed :100:

> the name of the key encryptedSettings is a poor choice I think

Yeah, not ideal either. We could go for a simple `metadata`.

wallet-{wallet-uuid} : The `walletId` should probably be stored in the object as well?

**Comment by nop33** [comment]
> wallet-{wallet-uuid} : The walletId should probably be stored in the object as well?

That wouldn't be necessary, but we could.

**Comment by mvaivre** [comment]
> That wouldn't be necessary, but we could.

My instinct tells me that we should :) That's what I'd expect in any kind of storage solution (DBs...).

**Comment by nop33** [comment]
Closing since it's merged in v2.0 branch
