### ISSUE TITLE
wallet problems

### ISSUE THREAD

**Issue by makar2186** [alephium/desktop-wallet#518]
Hello. when I go into my wallet, the contents disappear - a white sheet.

**Comment by mvaivre** [comment]
Hello, have you tried installing the [latest version](https://github.com/alephium/desktop-wallet/releases/tag/v1.5.0)?
If yes, which OS are you running on?

**Comment by makar2186** [comment]
no.

**Comment by makar2186** [comment]
and will it pour over the top or will you have to enter a new phrase?

**Comment by makar2186** [comment]
all goode thanks
