### ISSUE TITLE
Discuss select modals

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#523]
We currently have 2 ways of implementing a "select" feature. One opens a simple popup and another opens a modal. What about unifying the UI of "selecting" something? Would that make sense? The simple popup can handle relatively short lists, with simple values (number|string). The modal is much more flexible and scrollable but requires 2 clicks for selection, which can get annoying.

💡 Ideas:
- Make the simple popup able to handle more complicated values (`ReactNode`) and make sure it works well with long lists (scrollable)
- Close the select modal when the user clicks on one of the options (do not require 2 clicks)

Here are some examples:

## Selecting a wallet, theme, language, network

<img width="658" alt="image" src="https://user-images.githubusercontent.com/1579899/218997962-dd7a72dc-6e66-4879-9f93-0b4fbd794fcc.png">

<img width="911" alt="image" src="https://user-images.githubusercontent.com/1579899/218998809-a7c8c291-25f6-420f-98d0-e0a42d44ef34.png">

<img width="967" alt="image" src="https://user-images.githubusercontent.com/1579899/218998860-d96dd544-6211-40fd-bc27-0ead35cfdd98.png">

<img width="773" alt="image" src="https://user-images.githubusercontent.com/1579899/218998918-9a99cf5a-804b-402b-bcde-efb5475627a2.png">

## Selecting an address

<img width="642" alt="image" src="https://user-images.githubusercontent.com/1579899/218998134-6a38f8ce-b3e0-4ca7-a6d5-2d5ffa7dc421.png">

## Selecting a contact

I guess here it makes sense to have a "more complicated" modal view, since we can also search through the list. But again, it requires 2 clicks, not great.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/1579899/218998306-991f7c4a-6831-4a7f-9e1d-b55d2ef808f7.png">

**Comment by mvaivre** [comment]
You read my mind! I 💯 agree. I thought about this when I started to rework the select modal.

What I would do: 
- Allow select's option items to be ReactNodes, as you suggested. 
- Add an optional search input at the top. To make this flexible, the `option` component could receive a `searchTags: string[]` prop. Ex: a contact option could have `searchTags={['Mika', '1BBEMJQp....']}` which would allow searching for both the contact name or the address hash.

About the contact modal: I think that I would remove the shortcut to create a new contact. When sending a transaction, I'd rather have users really focusing on the sending process and not add further distraction. 

What we could do instead : when the transaction has been sent, if the recipient address isn't in the contact list, we could display a popup saying "Would you create a contact for {addressHash}?", with a little paragraph explaining why it can be useful. 
This popup could be dismissed and the user could choose not to show it anymore. 

WDYT?

**Comment by mvaivre** [comment]
![image](https://user-images.githubusercontent.com/6715943/219256198-4e2d867d-a1b3-485a-9f4f-9098ac5dd93d.png)

**Comment by nop33** [comment]
I really like your proposals! 🚀 On it!

**Comment by nop33** [comment]
Closing since it's merged in v2.0 branch
