### ISSUE TITLE
Add Translation disclaimer

### ISSUE THREAD

**Issue by MaudSimon** [alephium/desktop-wallet#545]
**Is your feature request related to a problem? Please describe.**
As the desktop wallet is developed in English and all the translations are provided by community members, the accuracy of the translations cannot be guaranteed. 

**Describe the solution you'd like**
I think we need to add a disclaimer when a user is switching to a language than isn't the wallet's native language. Something along the lines of: "“The desktop wallet is developed in English. Translations in other languages are provided by the Alephium community and may contain inaccuracies. In case of doubt, always refer to the English version”.
Or even shorter "The desktop wallet is developed in English. Translations in other languages are provided by the Alephium community. In case of doubt, always refer to the English version."

**Comments**
I would have this disclaimer in any future app were the translations cannot be guaranteed 100%.

**Comment by nop33** [comment]
@mvaivre, I think @MaudSimon would like this to be added to the wallet in the next release. It could be as simple as a small ⚠ icon with the message as a tooltip.

**Comment by mvaivre** [comment]
Yes, let's do this. Let's show the icon next to the setting's title only when the language isn't English
