### ISSUE TITLE
More explicit warning in the Review screen when setting a Lock Time 

### ISSUE THREAD

**Issue by MaudSimon** [alephium/desktop-wallet#548]
Feedback from the community: "Lets say I want to send coins with lock time.Then I send not a small amount with a locktime until 2023 but instead 2023 I write 2032 and I dont check it again, the coins are gone for the next 10 years. 

**Describe the solution you'd like**
"So, if you set a lock time, I would think it would be better to implement a warning with "please check the correct date you want to lock your coins and press okay"."

**Additional context**
The review screen is easy to mindfully click through which can make it easy for inattentive users to make mistakes.

**Comment by mvaivre** [comment]
Yes, I think so, and I agree with you. But IMO if we need more time to deliver the features and quality expected, that's ok. 1-2 weeks don't make a difference in the long run.

**Comment by nop33** [comment]
Would something like this meet our requirements?

![Image](https://user-images.githubusercontent.com/1579899/228227344-949846de-c34f-493a-b910-407befc95b7e.png)


![Image](https://user-images.githubusercontent.com/1579899/228227563-1d28d081-6cdc-4d1e-903d-2fc2874248ae.png)


![Image](https://user-images.githubusercontent.com/1579899/228227651-9a421771-6f25-4eab-8e00-020f4a255e0d.png)

**Comment by mvaivre** [comment]
> Would something like this meet our requirements?

I think it would!

**Comment by nop33** [comment]
Closing since it's merged in v2.0!
