### ISSUE TITLE
I only see white screen when I open my wallet

### ISSUE THREAD

**Issue by LakayMark** [alephium/desktop-wallet#550]
Hi All,

I imported my wallet to a newly  installed wallet in windows 11 but I only see white space all over the wallet? I cannot see my ballance
![Alepium wallet](https://user-images.githubusercontent.com/127012681/222949242-1860084a-7715-44a9-a1c9-4fa62e52059d.png)

**Comment by mvaivre** [comment]
Hi, I've you installed the newest version? 

https://github.com/alephium/desktop-wallet/releases/tag/v1.5.2

**Comment by LakayMark** [comment]
all good now
