### ISSUE TITLE
Show an error screen instead of a white screen when an error happens

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#551]
We should find a way to avoid showing nothing (white screen) when a bug happens. Goal is to avoid [this](https://github.com/alephium/desktop-wallet/issues/550).
We could show a nice friendly design with a couple of tips (download latest version, restart the app, open issue on GH...)

**Comment by nop33** [comment]
I believe that this white screen will not appear in newer versions of the wallet since we have the upgrade message which will lead users to upgrade before they login. But yes, it'd be great to avoid having this white screen in the cases where people choose to not upgrade and unlock their wallets.

**Comment by nop33** [comment]
I think this would be solved if we implement https://github.com/alephium/alephium-frontend/issues/38

Closing.
