### ISSUE TITLE
AssetList: allow to show/hide unknown tokens

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#556]
We should :

1) Display unknown tokens properly (use a hash instead of a name, use no ticker etc.)
2) Allow to show or hide unknown token by default. It should probably be shown by default(?)

**Comment by nop33** [comment]
Another problem we are facing is that if we don't know the metadata, we don't know the number of decimals, and without the decimals, we don't know how to format the bigint number we receive from the API:

<img width="880" alt="image" src="https://user-images.githubusercontent.com/1579899/223434116-be930c0f-c756-4d2f-a017-68beef477a69.png">

**Comment by nop33** [comment]
I propose that if we encounter tokens where we have no metadata for to display a message that says `"unrecognised token"` (or sth like that) with the hash next to it. No amounts.

**Comment by nop33** [comment]
Just read @mvaivre's message on Slack:

> I agree that we should only display known tokens by default
> For unknown tokens, I would “notify” the user of their presence (ie. a little tag saying how many unknown tokens are hidden) + add an option to always display unknown tokens.
> Unknown tokens should be displayed with a little tag saying that they are unverified.

**Comment by nop33** [comment]
I'll proceed with this once we have taken some decisions regarding how to display this information.

**Comment by mvaivre** [comment]
If we want to be able to properly display tokens, users will need to provide the ticker + the number of decimals.
Metamask does this :

<img width="238" alt="image" src="https://user-images.githubusercontent.com/6715943/223513338-a7cae631-6c40-49a5-ab18-251d31210093.png">

<img width="355" alt="image" src="https://user-images.githubusercontent.com/6715943/223513455-f04a72cf-a2f5-402e-8fd9-7ddfb27db87d.png">

I've started to work on a design.

**Comment by nop33** [comment]
The design is still work in progress, right?

FYI, this is how the current stage of the v2.0 displays unknown tokens:

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/1579899/224703041-8f6c7a05-5009-4bc1-a826-d8b978033993.png">

For reference, the extension wallet does not display tokens that are unknown in the assets list and allows the user to import tokens, just like Metamask. However, in the transfers screen, it does display them.

<img width="356" alt="image" src="https://user-images.githubusercontent.com/1579899/224704260-45d86043-df06-4092-af72-128122cb540a.png"> <img width="358" alt="image" src="https://user-images.githubusercontent.com/1579899/224704323-e8662234-f5a5-4871-8fd0-5ebe0c866ace.png">

BTW, if you haven't realized, I used the same testnet wallet for all screenshots above (both desktop & extension wallets)

**Comment by mvaivre** [comment]
I don't have the design ready yet, but that's on purpose ;) I suggest we start simple by showing unknown tokens like I do in the explorer: 

<img width="680" alt="image" src="https://user-images.githubusercontent.com/6715943/224813479-9362a2a5-bb22-400b-b574-8b1f7a03856b.png">

You can check my branch `transaction-row-details` for details.

This should work in the beginning as few tokens are available. I suggest that we move adding filtering option to v2.x. WDYT?

**Comment by nop33** [comment]
Agreed 👍 One comment tho: I am not a big fun of these characters: "???" I think we could remove them completely and keep the "Raw amount" label below it (smart idea btw to add this label).

**Comment by nop33** [comment]
This is my proposal



![Image](https://user-images.githubusercontent.com/1579899/225061121-151cc3fe-44f4-46d5-9f7b-f7189f02a298.png)
