### ISSUE TITLE
Trim password

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#560]
It might be that when users are pasting their passwords, they copy whitespace or empty lines with it. Let's make sure to trim the password before checking if it's the correct one.

Also, let's verify that the "Invalid password" message is only shown when the password is wrong and not when another error happens.

**Comment by nop33** [comment]
We should pay attention here! There might be users that already have wallets with passwords that include whitespaces and new lines! When we implement the code that trims the password before checking if it's valid, it should also check the password without trimming. Otherwise, some people might not be able to unlock their wallets.

**Comment by mvaivre** [comment]
Exactly. And I'm not sure if it's really our job to trim the password, I don't know of any other service doing this. 

I would first focus on the second part of you issue:

> Also, let's verify that the "Invalid password" message is only shown when the password is wrong and not when another error happens.

💯

**Comment by nop33** [comment]
> Also, let's verify that the "Invalid password" message is only shown when the password is wrong and not when another error happens.

Just FYI, we already took care of that in the last release.

**Comment by nop33** [comment]
I agree that it shouldn't be our job to trip a password. Closing issue.
