### ISSUE TITLE
Implement new Addresses page layout with scrolling effect

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#566]

**Comment by nop33** [comment]
We still need to clarify here whether we keep the bottom row "Show advanced operations" or we use the button proposed for opening a side panel.

**Comment by mvaivre** [comment]
Let's go with the side button + side panel! I've update the mockup in sigma. 
Cards in the side panels will obv. be stacked vertically :

<img width="742" alt="image" src="https://user-images.githubusercontent.com/6715943/223795111-c806a08c-e55a-46aa-bbe4-ccab06081f26.png">

Let's put "Discover addresses" as the first item in the list as it will probably be the most used.

**Comment by nop33** [comment]
Closing since it's merged in v2.0!
