### ISSUE TITLE
After Login - Alephium - Desktop-Wallet (No image)

### ISSUE THREAD

**Issue by baeget** [alephium/desktop-wallet#576]
After login, desktop-wallet (changes with No image) attached.
![Wallet - No image(after login)](https://user-images.githubusercontent.com/99034727/224507855-25535317-6e43-41ec-a5af-a16bdd490fa6.jpg)

How to fix it ?

**Comment by mvaivre** [comment]
Please update to the latest version : https://github.com/alephium/desktop-wallet/releases/tag/v1.5.3

**Comment by mvaivre** [comment]
Closing because of no response. Feel free to get support [on our Discord](https://discord.com/invite/XsGpZ5VDTM) if the problem persists (it should not ;)). Thanks!
