### ISSUE TITLE
Update tx pagination logic

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#596]
See https://github.com/alephium/desktop-wallet/pull/588#discussion_r1142989469

> // How do we handle paging when addresses filtering changes? We need to keep track of the loaded page for every
  // combination of selected addresses and in general all filtering criteria. That sounds very complex. Is there a
  // simpler way? What if no matter what the filtering criteria are, we always:
  // 1. fetch the next page of ALL addresses
  // 2. check to see if we received any results
  // 3. filter the results
  // 4. if the filter results are 0 but the results are not 0, fetch again

**Comment by nop33** [comment]
@mvaivre just to keep in mind that since the solution we agreed upon relies on a recursive method of calling the API until we receive results that meet the filtering criteria, we might end up in a situation where the recursive function downloads the whole transaction history.

Maybe we should limit it to, say, 10 recursive calls. Then the user can click "load more" again. WDYT?

**Comment by mvaivre** [comment]
Sounds like a reasonable compromise to me!

**Comment by nop33** [comment]
Already implemented :D

**Comment by nop33** [comment]
Closing since it's merged in v2.0!
