### ISSUE TITLE
Wallet relies on full node endpoint only ?

### ISSUE THREAD

**Issue by polarker** [alephium/desktop-wallet#6]

**Comment by mvaivre** [comment]
@polarker can we close this?

**Comment by polarker** [comment]
@mvaivre the idea is to remove the dependency on explorer-backend's endpoint. Which part do we need the host of explorer-backend ?

**Comment by mvaivre** [comment]
Ah, I didn't understand the task properly then. 
The explorer backend is used to get all the read-only values (balances, transactions...). We did that to offload the node.
The node is only called when sending a TX.

cc/ @tdroxler

**Comment by polarker** [comment]
> Ah, I didn't understand the task properly then. The explorer backend is used to get all the read-only values (balances, transactions...). We did that to offload the node. The node is only called when sending a TX.
> 
> cc/ @tdroxler

I see, thanks ! Let's close this for now. I will investigate metamask a bit more, as they seems to do differently
