### ISSUE TITLE
My Alephium desktop doesn't show history transaction and balance. 

### ISSUE THREAD

**Issue by zergriver** [alephium/desktop-wallet#605]
Hi Alephium team, 

My account name is Dreamer (my email is zergriver@gmail.com). I can't find all my history transactions and balance show on my alephium desktop wallet. How can I get them back? or where I can find them? 

Thank you.

Jiang

**Comment by nop33** [comment]
Hello @zergriver, please find some help on our Discord server! Thanks! https://alephium.org/discord
