### ISSUE TITLE
Opening address side modal is a bit laggy

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#615]
This is introduced after the charts where implemented

**Comment by mvaivre** [comment]
May be related to this:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/6715943/232956826-14df81de-1761-4957-bb8d-7f67b59b854e.png">

**Comment by nop33** [comment]
Ha, didn't notice this before... Not sure it happened while I was testing. Will investigate.

**Comment by nop33** [comment]
It most probably is because of that 😅

**Comment by nop33** [comment]
I fixed the re-rendering issue but the glitch persists.

**Comment by nop33** [comment]
merged, closing
