### ISSUE TITLE
Is there anyone working on the Simplified Chinese (ZH) translation? 

### ISSUE THREAD

**Issue by DominicTing** [alephium/desktop-wallet#626]
About half a year ago, I discovered Alephium through GPU mining, and downloaded and used its GUI. As of now, there is no ZH translation for the desktop application. If no one else is working on this, I'd love to contribute a ZH translation.

**Comment by polarker** [comment]
Hey @DominicTing, we are improving the translation tools so that it's easier to support new languages. Thanks for reachign out. We will ping you once it's ready.
