### ISSUE TITLE
Enable copy of address from address badge

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#675]
@JKtranslator proposed today that he was trying to copy his main address from the address badge in the app header and he couldn't. He specifically said (I'm paraphrasing):

> Since you asked me to send you my address so that you send me some testnet tokens, I had to look for the right place to copy it.

**Comment by nop33** [comment]
@VDAODAO also reported that he was trying to copy the address hovering the address hash but he couldn't. I think we should have it enabled everywhere imo. The users can easily get used to the idea and then it's problematic when it's not possible to copy it in some cases:

> WISH - everywhere else in the app, i can copy the adress from the little two boxes on the right of the adress. Here I spent 5' to find that the copy button was below the QR code. I understand this probably comes from ledger, but in terms of coherence it’s just a bit counterintuitive 
>  ![image](https://user-images.githubusercontent.com/1579899/236022438-47da0cec-2729-4bea-90dc-24c9a240f9ef.png)

**Comment by mvaivre** [comment]
Mhh ok. Let's keep the disableCopy prop though. In some places (in selects for instance) I found this to be distractive.
