### ISSUE TITLE
Improve UX of choosing an asset when sending a tx

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#680]
> the “add asset” concept that i need to click and that it automagically appears one more every time is weird in terms of design: it should be something like a drop down where i select the asset i want to send, no?

I replied that:

> You can click on the asset name (initially it’s "Alephium") and then the dropdown appears. The “Add asset” is only when you want to send multiple. But thanks for the feedback, apparently it’s not clear enough!

**Comment by mvaivre** [comment]
Yeah, if you are not used to be able to send multiple assets in one tx, this may be confusing. That's the kind of places where we should educate our users with a little info message I believe.

**Comment by nop33** [comment]
great ideas 💯
