### ISSUE TITLE
Clarify why there's an extra 0.01 ALPH per token added in the tx

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#682]
It's confusing that when sending tokens, there's an additional `0.01` ALPH per token that is added to the transaction. The UI should clarify why this is happening. 

@polarker could you please remind me of the reason so that I can think of how to best present this info to the user?  Was it because every UTXO should have a small amount of ALPH for some technical reason?

thx!

**Comment by polarker** [comment]
The 0.01 ALPH is the minimal requirement per UTXO to avoid utxo spamming. There are usually two outputs in a simple token transaction, one for the recipient and another one for change output. That's why you see 0.02 ALPH in the output.

**Comment by polarker** [comment]
Here is the definition in the web3 SDK: https://github.com/alephium/alephium-web3/blob/master/packages/web3/src/constants.ts#L24

**Comment by mvaivre** [comment]
Yep, agreed, we should add an info icon redirecting to a paragraph in the docs.
Also, I'd make sure that the token(s) to send are displayed above the amount in ALPH in cases like this, WDYT?

**Comment by nop33** [comment]
Good point.

That means we need a paragraph in the docs :)
