### ISSUE TITLE
Alph didnt arrive in my exchange account 

### ISSUE THREAD

**Issue by Dannywat61** [alephium/desktop-wallet#687]
Hi yesterday about 24 hours ago at least i sent 400 alph to my Bitmart account they didnt arrive tripple checked address all go yet today i sent 450 Alph to same account same address and they arrived with in the hour ,please help me .
Bitmart doesnt have any support/help working .
Waiting for your reply  thaning you Danny Watson.

**Comment by nop33** [comment]
You could enter the Bitmart deposit address on the explorer to check if your coins arrived. Then, it's up to Bitmart to clarify with you why they don't show on your account. Not much else we can do!
