### ISSUE TITLE
'revoked' signature in Windows 2.0 build

### ISSUE THREAD

**Issue by diomark** [alephium/desktop-wallet#701]
This was initially reported SURESHKORADA on discord but confirmed by me.

The certificate in the Alephium-2.0.0.exe windows binary is revoked.

![image](https://github.com/alephium/desktop-wallet/assets/20622085/1f57db83-2b87-4110-904c-b06df38cda9c)

![image](https://github.com/alephium/desktop-wallet/assets/20622085/4fae5883-7dd7-4511-b1aa-0284818978ea)

This didn't cause me any issues but for him, it resulted in Windows complaining about an invalid certificate and not installing.

**Comment by nop33** [comment]
@killerwhile could you please have a look when you have the time? Thanks!

**Comment by nop33** [comment]
I am getting the same prob;em on windows:

> Error: New version 2.0.0 is not signed by the application owner: publisherNames: Panda Software SA, raw info: { "SignerCertificate": { "FriendlyName": "", "IssuerName": { "Name": "CN=SSL.com Code Signing Intermediate CA ECC R2, O=SSL Corp, L=Houston, S=Texas, C=US", "Oid": "System.Security.Cryptography.Oid" }, "NotAfter": "/Date(1705135759000)/", "NotBefore": "/Date(1673686159000)/", "PrivateKey": null, "PublicKey": { "Key": null, "Oid": "System.Security.Cryptography.Oid", "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData", "EncodedParameters": "System.Security.Cryptography.AsnEncodedData" }, "SerialNumber": "09CE4B69F2625F925E4D32ECAA07084C", "SignatureAlgorithm": { "Value": "1.2.840.10045.4.3.3", "FriendlyName": "sha384ECDSA" }, "Thumbprint": "E6180400CE9241818062D82287E55E8C82163E05", "Version": 3, "Issuer": "CN=SSL.com Code Signing Intermediate CA ECC R2, O=SSL Corp, L=Houston, S=Texas, C=US", "Subject": "CN=Panda Software SA, O=Panda Software SA, L=Neuchâtel, C=CH" }, "TimeStamperCertificate": { "Archived": false, "Extensions": [ "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension", "System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension", "System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension", "System.Security.Cryptography.X509Certificates.X509Extension", "System.Security.Cryptography.X509Certificates.X509Extension", "System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension", "System.Security.Cryptography.X509Certificates.X509Extension", "System.Security.Cryptography.X509Certificates.X509Extension" ], "FriendlyName": "", "IssuerName": { "Name": "CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA, O=\"DigiCert, Inc.\", C=US", "Oid": "System.Security.Cryptography.Oid" }, "NotAfter": "/Date(2016230399000)/", "NotBefore": "/Date(1663718400000)/", "HasPrivateKey": false, "PrivateKey": null, "PublicKey": { "Key": "System.Security.Cryptography.RSACryptoServiceProvider", "Oid": "System.Security.Cryptography.Oid", "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData", "EncodedParameters": "System.Security.Cryptography.AsnEncodedData" }, "SerialNumber": "0C4D69724B94FA3C2A4A3D2907803D5A", "SubjectName": { "Name": "CN=DigiCert Timestamp 2022 - 2, O=DigiCert, C=US", "Oid": "System.Security.Cryptography.Oid" }, "SignatureAlgorithm": { "Value": "1.2.840.113549.1.1.11", "FriendlyName": "sha256RSA" }, "Thumbprint": "F387224D8633829235A994BCBD8F96E9FE1C7C73", "Version": 3, "Handle": 1992254032384, "Issuer": "CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA, O=\"DigiCert, Inc.\", C=US", "Subject": "CN=DigiCert Timestamp 2022 - 2, O=DigiCert, C=US" }, "Status": 1, "StatusMessage": "A certificate was explicitly revoked by its issuer" }

**Comment by killerwhile** [comment]
Certificate has now been regenerated and updated in the action variables. A new version will be provided shortly.

**Comment by nop33** [comment]
Thanks @killerwhile <3

> A new version will be provided shortly.

What does this mean? Does that mean we need to release a new version (2.0.1)?

**Comment by nop33** [comment]
@killerwhile I am trying to release a new patch version, but the mac build is failing, is it related to this issue or is it a new one?

https://github.com/alephium/desktop-wallet/actions/runs/4948710359/jobs/8849954801

```
security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)
```

**Comment by nop33** [comment]
@killerwhile I made a new rc, downoaded it, and inpect the exe file. Is it normal to see this?

![image](https://github.com/alephium/desktop-wallet/assets/1579899/d09dde85-784a-4b7b-aa65-17d9f4ef9496)

**Comment by nop33** [comment]
I just noticed that I cannot inspect the certficate of the 2.0.1. Here is a comparison of the properties window with 2.0.0. There is no "Digital signatures" tab.

![image](https://github.com/alephium/desktop-wallet/assets/1579899/adcf838f-bdb0-40c3-a7e7-ed8e9bcfe22b)

**Comment by nop33** [comment]
FWIW, the action that signed the [2.0.1-rc.3 ](https://github.com/alephium/desktop-wallet/actions/runs/4960669326/jobs/8876456994)looks identical to the one that signed the [2.0.1](https://github.com/alephium/desktop-wallet/actions/runs/4978051130/jobs/8907858538).
