### ISSUE TITLE
Wallet/locked coins

### ISSUE THREAD

**Issue by Waldi28** [alephium/desktop-wallet#719]
Played around with the lock time in the wallet and found these bugs.

1. If I type the locktime without mouseclicks i get 6 numbers in the year. example: 19.05.202344 --:--

2. When I use the arrow keys on the keyboard to go back or forward by 1 year, the number 275760 appears as the year before 2023, maybe it could be stopped by 2023 or the actual year. 

3. After setting the lock time, for example: 20.05.2024 10:00, if I want to correct the year afterwards, it jumps to 1901, and I can only change the last digit, from 1901 to 1909. 

4.  When I hover over the field, strangely I get a pop-up in German even though the wallet is set to English. Gib einen gültigen Wert ein, das Feld ist nicht vollständig...

**Comment by mvaivre** [comment]
Thanks a lot for reporting this 🙏  
We're gonna take a look asap and hopefully ship a fix in the next release.

**Comment by nop33** [comment]
Hm, I can't reproduce the wrong language tooltip issue...

<img width="539" alt="image" src="https://github.com/alephium/desktop-wallet/assets/1579899/be9fe134-96d2-4e0e-b9d2-28f66282c1ed">

This value seems to be set by the browser itself, for the `datetime-local` input field type. At least the error message in red that we display is in the correct language :)
