### ISSUE TITLE
Tokens support

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#72]
We need to support displaying tokens (name, amount) in our main wallet, and allow for sending them around.

Features

- [ ] https://github.com/alephium/alephium-js/issues/10

**TBD**

**Comment by nop33** [comment]
We will need a slight redesign of the Send modal if we are to be able to send tokens, right?

**Comment by nop33** [comment]
Ah, I completely forgot about the send modal redesign! So sweet!



![Image](https://user-images.githubusercontent.com/1579899/219025379-4f163289-c6eb-4be9-a4c7-588f237ff0ab.png)

**Comment by nop33** [comment]
Something we need to consider is that the user should (probably, awaiting Slack answers) be able to send different kinds of assets, as well as ALPH, within one transaction.

**Comment by mvaivre** [comment]
Thanks for your initial design, nice! Here's a couple of updated modals (available in Figma) :

![image](https://user-images.githubusercontent.com/6715943/219141998-f7e4f31e-99ad-4acd-a5ab-5cf109402f70.png)

![image](https://user-images.githubusercontent.com/6715943/219142087-92f260b1-7340-4aa1-9e6f-59d5cae4cbeb.png)

**Comment by nop33** [comment]
Awesome job man! Will work on this tmr
