### ISSUE TITLE
Alephium Wallet 

### ISSUE THREAD

**Issue by 369firefish** [alephium/desktop-wallet#726]
Hi, I have just updated to the new version of the wallet, and my laptop shut down.  I have rebooted and an old version of the Alephium wallet came up on the screen, but it obviously isn't my wallet, as it doesn't accept by pw.  Can you please help and advise as to what to do to restore my wallet,  thanks

**Comment by mvaivre** [comment]
Hi!
1) As always, please verify that you have your recovery phrase stored in a safe place. As long as you have your phrase, no need to worry.
2) Make sure that your password is correct (caps lock?)
2) Make sure that you're running the [latest version of the wallet](https://github.com/alephium/desktop-wallet/releases). It seems like the unexpected reboot of your laptop prevented the update to succeed.
3) If you're still unable to unlock your wallet, simply use the "Import Wallet" feature with your recovery phrase to recover your wallet.

**Comment by 369firefish** [comment]
HiThank you for responding.I found the wallet.  The upgrade resulted in it being saved in a very different area of the hard drive!  Nigel Sent from my iPhoneOn 5 Jun 2023, at 06:42, Mikaël Vaivre ***@***.***> wrote:﻿
Hi!

As always, please verify that you have your recovery phrase stored in a safe place. As long as you have your phrase, no need to worry.
Make sure that your password is correct (caps lock?)
Make sure that you're running the latest version of the wallet. It seems like the unexpected reboot of your laptop prevented the update to succeed.
If you're still unable to unlock your wallet, simply use the "Import Wallet" feature with your recovery phrase to recover your wallet.
