### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'transactions')

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#727]
<img width="1040" alt="image" src="https://github.com/alephium/desktop-wallet/assets/6715943/030d16e6-57c9-4b94-ac3e-ccbfa1b3c07d">

Happens after locking a wallet.

**Comment by nop33** [comment]
In which branch does this happen?

**Comment by mvaivre** [comment]
In `next`

**Comment by mvaivre** [comment]
Nope! 🌞
