### ISSUE TITLE
Improve error handling when not enough ALPH is available to cover transaction fees

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#734]
Monitor error handling progress on the node. If needed, patch this on the client side by specifying which asset amount isn't enough and properly format amounts for display.

![image](https://github.com/alephium/desktop-wallet/assets/6715943/643ed3c4-d30d-4fd5-a700-7ea2f0b6998f)

**Comment by nop33** [comment]
Duplicate of https://github.com/alephium/desktop-wallet/issues/734

Closing.
