### ISSUE TITLE
macOS notarization fails

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#739]
When I tried to release the 2.0.2 patch release, I got this error. I tried re-running the actions, but the error remains:

>   ⨯ ❌ Notarization Error,please check notarization-error.log  failedTask=build stackTrace=Error: ❌ Notarization Error,please check notarization-error.log

https://github.com/alephium/desktop-wallet/actions/runs/5343514862/jobs/9688053842

**Comment by mvaivre** [comment]
cc/ @killerwhile
