### ISSUE TITLE
appimaged removes %U from Exec key in .desktop file.

### ISSUE THREAD

**Issue by gnusuari0** [alephium/desktop-wallet#782]
The Exec key should read "Exec=/home/user/bin/Alephium-2.1.2.AppImage %U" but when appimaged registers the AppImage package and installs the .desktop file the parameter %U is removed.

1. Download AppImage.
2. Move it to a folder watched by appimaged.
3. Wait for appimaged to register the AppImage.
4. Try to connect Alephium Wallet with DEX ayin.app.
5. Alephium Wallet opens but no message to sign transaction appears.

**Expected behavior**
The %U parameter should not be removed by appimaged. Alephium Wallet must be able to connect with dApps.

[appimagekit_edcb455c60018fcf54477fb8744f6db1-alephium-wallet.desktop.txt](https://github.com/alephium/desktop-wallet/files/12352214/appimagekit_edcb455c60018fcf54477fb8744f6db1-alephium-wallet.desktop.txt)

**Comment by nop33** [comment]
Thanks for the report @gnusuari0! 

We have actually configured the `.desktop` file to include the `%U` parameter in the `exec` property, as seen here: https://github.com/alephium/desktop-wallet/blob/master/package.json#L139-L141. I can see that in your txt file the `exec` property is correctly set to `exec=alephium %U`. However, this might be different than the `Exec` one that you mentioned.

Nevertheless, I did not manage to reproduce the problem. I've spin up a VM, built an arm64 app (I can't use the amd one from GH on my machine), run the AppImage, opened ayin.app, and I could successfully connect to it using the desktop wallet:

https://github.com/alephium/desktop-wallet/assets/1579899/8ca0a3a0-0771-4acd-86a6-5b5abeff427c

I'll try to find someone with an amd machine to do another test.

We would also greatly appreciate help from the community on this one!

**Comment by gnusuari0** [comment]
Thank you for your fast reply. I think the problem is that I'm using an old version of AppImageD. Regarding the `exec` key in the file, it's not in the FreeDesktop standard, so it's not being parsed unless the caller supports that extension. The command `desktop-file-validate` reports that if it's a custom parameter it should start with `X-`.
