### ISSUE TITLE
1D chart isn't displaying anything

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#788]

**Comment by racnar777** [comment]
I cannot move tokens  out of any wallets, API failure and too many gas fees?,,

**Comment by racnar777** [comment]
I have a lot of alephium I am stuck with right now.

**Comment by nop33** [comment]
@racnar777 does this help? https://docs.alephium.org/wallet/desktop-wallet/advanced-features#1-utxo-consolidation

**Comment by racnar777** [comment]
Ill try that thanks
