### ISSUE TITLE
Multiple dapp connections

### ISSUE THREAD

**Issue by polarker** [alephium/desktop-wallet#796]
Right now, if a new dapp is connected, the existing dapp connection will be closed. It's not convenient sometimes. For example, a user might want to connect to DEX, dapp aggregator, trading analysis platforms at the same time.

Walletconnect supports multiple connections by default, we could add the logic code without much effort, same for the UI I guess.

Priority: not urgent from my perspective.

**Comment by nop33** [comment]
I've implemented this feature on the mobile wallet side, it's still being reviewed in a PR. I'll soon port the code to the desktop wallet.

**Comment by nop33** [comment]
This feature is merged in the monorepo, closing.
