### ISSUE TITLE
Dapp connection loss when changing webpage

### ISSUE THREAD

**Issue by MaudSimon** [alephium/desktop-wallet#800]
**Describe the bug**
When using the https://walph.io/ website, when I connect on the homepage, then select a "walph", I lose the desktop wallet connection and need to reconnect. The same thing happens when I return to the homepage, I need to reconnect my wallet.  

**To Reproduce**
1. Go to https://walph.io/
2. Connect to your desktop wallet
3. Select a walph to participate in
4. See wallet connection loss.

**Expected behavior**
I shouldn't lose the connection while interacting with the same dapp.

**Environment**
 - OS: Mac
 - Version Ventura 13.4.1.
 - Latest desktop wallet version v2.1.5

**Additional context**
I just tested on Deadrare.io and I am not losing the connection to the desktop wallet so it might be walph.io specific.

**Comment by nop33** [comment]
Ayin, deadrare, our own nft marketplace, tooklit, all these are web apps and handle links accordingly (when clicking on links you don’t see the whole page refreshing). Walph seems to be a website where every click loads a new page from scratch. This is not necessarily a bad thing, they just need to re-establish the WalletConnect connection. The same happens with Ayin, Deadrare, etc when you refresh the page (Cmd+R / Ctrl+R).

**Comment by MaudSimon** [comment]
Great I guess I can close this.
