### ISSUE TITLE
Cannot send tokens out of wallet.

### ISSUE THREAD

**Issue by racnar777** [alephium/desktop-wallet#817]
I get an error on all wallets desktop extension and mobile app.
It reads:

"" Error while building transaction: Error: [API Error] - Estimated gas GasBox(1345740) too large, maximal GasBox(625000). Consider consolidating UTXOs using the sweep endpoints""

I am beyond frustrated.

Have mercy please help.

**Comment by nop33** [comment]
We will release a fix for this this week. In the meantime, this should be helpful: https://docs.alephium.org/wallet/desktop-wallet/advanced-features#1-utxo-consolidation
