### ISSUE TITLE
Wallet is all white

### ISSUE THREAD

**Issue by mtbrown4ayl** [alephium/desktop-wallet#821]
I recently got the wallet. It seemed fine til my first deposit went in and now i just have an all white screen. any ideas?
![Screenshot 2024-02-09 074253](https://github.com/alephium/desktop-wallet/assets/42585863/26c4b0df-f16a-420a-8b37-b78f0f828467)

**Comment by nop33** [comment]
which version of the wallet are you using?

**Comment by mtbrown4ayl** [comment]
1.1.0.0

**Comment by mtbrown4ayl** [comment]
I just updated it to 2.2.2.0 and it is working fine. Im not sure why it ended up downloading such an old version the first time. Sorry the confusion!
