### ISSUE TITLE
Error of storage are not caught in wallet, or it is expect ?

### ISSUE THREAD

**Issue by polarker** [alephium/desktop-wallet#9]

**Comment by nop33** [comment]
More info needed

**Comment by mvaivre** [comment]
@polarker Could you provide more info? Thanks!

**Comment by polarker** [comment]
Yes, I will provide more information when I have a bit of time

**Comment by nop33** [comment]
Is this still relevant? :)

**Comment by polarker** [comment]
I don't think it's a problem since nobody reports it

**Comment by nop33** [comment]
Alright. I'll close it then and re-open if we get a report!
